/* Generated by Yosys 0.65+37 (git sha1 e87a9bd9a, clang++ 18.1.8 -fPIC -O3) */

module M05_PowerManager(clk_aon, rst_aon_n, rst_por_n, bus_cmd_valid, bus_cmd_ready, bus_cmd_addr, bus_cmd_rw, bus_cmd_data, bus_rsp_valid, bus_rsp_data, bus_rsp_error, dvfs_op_req, dvfs_op_ack, dvfs_vdd_req, dvfs_freq_req, dvfs_busy, vdd_main_set, vdd_main_ack, vdd_main_ready, vdd_main_error, pg_main_en
, pg_main_status, pg_main_switch, pg_iso_en, pmode_state, pmode_req, pmode_ack, pmode_error, wakeup_ext, wakeup_en, wakeup_status, wakeup_pending, wakeup_clear, pwr_estimate, pwr_budget, pwr_alert, pwr_counters, activity_main, activity_io, activity_dram, idle_timeout, idle_detected
, pm_status, pm_irq, pm_irq_type);
  input clk_aon;
  wire clk_aon;
  input rst_aon_n;
  wire rst_aon_n;
  input rst_por_n;
  wire rst_por_n;
  input bus_cmd_valid;
  wire bus_cmd_valid;
  output bus_cmd_ready;
  reg bus_cmd_ready;
  input [15:0] bus_cmd_addr;
  wire [15:0] bus_cmd_addr;
  input bus_cmd_rw;
  wire bus_cmd_rw;
  input [31:0] bus_cmd_data;
  wire [31:0] bus_cmd_data;
  output bus_rsp_valid;
  reg bus_rsp_valid;
  output [31:0] bus_rsp_data;
  wire [31:0] bus_rsp_data;
  output bus_rsp_error;
  reg bus_rsp_error;
  output [1:0] dvfs_op_req;
  wire [1:0] dvfs_op_req;
  input dvfs_op_ack;
  wire dvfs_op_ack;
  output [2:0] dvfs_vdd_req;
  wire [2:0] dvfs_vdd_req;
  output [31:0] dvfs_freq_req;
  wire [31:0] dvfs_freq_req;
  input dvfs_busy;
  wire dvfs_busy;
  output [7:0] vdd_main_set;
  wire [7:0] vdd_main_set;
  input vdd_main_ack;
  wire vdd_main_ack;
  input vdd_main_ready;
  wire vdd_main_ready;
  input vdd_main_error;
  wire vdd_main_error;
  output pg_main_en;
  wire pg_main_en;
  input pg_main_status;
  wire pg_main_status;
  output pg_main_switch;
  reg pg_main_switch;
  output pg_iso_en;
  reg pg_iso_en;
  output [1:0] pmode_state;
  reg [1:0] pmode_state;
  input [1:0] pmode_req;
  wire [1:0] pmode_req;
  output pmode_ack;
  reg pmode_ack;
  output pmode_error;
  wire pmode_error;
  input [7:0] wakeup_ext;
  wire [7:0] wakeup_ext;
  output [7:0] wakeup_en;
  wire [7:0] wakeup_en;
  output [7:0] wakeup_status;
  wire [7:0] wakeup_status;
  output wakeup_pending;
  wire wakeup_pending;
  input wakeup_clear;
  wire wakeup_clear;
  output [15:0] pwr_estimate;
  wire [15:0] pwr_estimate;
  input [15:0] pwr_budget;
  wire [15:0] pwr_budget;
  output pwr_alert;
  reg pwr_alert;
  output [31:0] pwr_counters;
  wire [31:0] pwr_counters;
  input activity_main;
  wire activity_main;
  input activity_io;
  wire activity_io;
  input activity_dram;
  wire activity_dram;
  input [15:0] idle_timeout;
  wire [15:0] idle_timeout;
  output idle_detected;
  wire idle_detected;
  output [7:0] pm_status;
  wire [7:0] pm_status;
  output pm_irq;
  wire pm_irq;
  output [2:0] pm_irq_type;
  wire [2:0] pm_irq_type;
  wire [15:0] _000_;
  wire _001_;
  wire [7:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire [3:0] _009_;
  wire [3:0] _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire [11:0] _283_;
  wire [11:0] _284_;
  wire [11:0] _285_;
  reg activity_dram_stage0;
  reg activity_dram_stage1;
  reg activity_dram_sync_reg;
  reg activity_io_stage0;
  reg activity_io_stage1;
  reg activity_io_sync_reg;
  reg activity_main_stage0;
  reg activity_main_stage1;
  reg activity_main_sync_reg;
  reg [4:0] dvfs_state_reg;
  reg [7:0] dvfs_timeout_cnt_reg;
  reg pg_entering_reg;
  reg pg_exiting_reg;
  reg [3:0] pg_seq_cnt_reg;
  reg [3:0] pg_seq_state_reg;
  reg pm_error_reg;
  reg pm_ready_reg;
  wire [1:0] pmode_state_next;
  reg [1:0] pmode_state_reg;
  reg [15:0] pwr_budget_reg;
  assign _027_ = ~pg_seq_cnt_reg[0];
  assign _284_[2] = ~activity_io_sync_reg;
  assign _028_ = ~pmode_req[0];
  assign _029_ = pg_seq_state_reg[1] & ~(pg_seq_state_reg[0]);
  assign _030_ = _029_ & ~(pg_seq_state_reg[3]);
  assign _031_ = pg_seq_state_reg[2] & ~(pg_seq_state_reg[3]);
  assign _007_ = ~(_029_ & _031_);
  assign _008_ = ~_007_;
  assign _032_ = ~(bus_cmd_addr[0] | bus_cmd_addr[1]);
  assign _033_ = _032_ & ~(bus_cmd_addr[3]);
  assign _034_ = _033_ & ~(bus_cmd_addr[2]);
  assign _035_ = ~(bus_cmd_addr[5] | bus_cmd_addr[4]);
  assign _036_ = bus_cmd_addr[6] & ~(bus_cmd_addr[7]);
  assign _037_ = _035_ & _036_;
  assign _038_ = ~(bus_cmd_addr[10] | bus_cmd_addr[11]);
  assign _039_ = ~(bus_cmd_addr[8] | bus_cmd_addr[9]);
  assign _040_ = _038_ & _039_;
  assign _041_ = ~(bus_cmd_addr[14] | bus_cmd_addr[15]);
  assign _042_ = ~(bus_cmd_addr[12] | bus_cmd_addr[13]);
  assign _043_ = _041_ & _042_;
  assign _044_ = _040_ & _043_;
  assign _045_ = _037_ & _044_;
  assign _046_ = _034_ & _045_;
  assign _047_ = bus_cmd_valid & ~(bus_cmd_rw);
  assign _048_ = pwr_budget_reg[14] & _047_;
  assign _000_[14] = _046_ & _048_;
  assign _049_ = pwr_budget_reg[13] & _047_;
  assign _000_[13] = _046_ & _049_;
  assign _050_ = pwr_budget_reg[12] & _047_;
  assign _000_[12] = _046_ & _050_;
  assign _051_ = pwr_budget_reg[11] & _047_;
  assign _000_[11] = _046_ & _051_;
  assign _052_ = bus_cmd_addr[2] & _033_;
  assign _053_ = _045_ & _052_;
  assign _054_ = ~(_045_ & _052_);
  assign _055_ = ~(pwr_counters[10] & _053_);
  assign _056_ = ~(pwr_budget_reg[10] & _046_);
  assign _057_ = ~(_055_ & _056_);
  assign _000_[10] = _047_ & _057_;
  assign _058_ = ~(bus_cmd_addr[6] | bus_cmd_addr[7]);
  assign _059_ = _035_ & _058_;
  assign _060_ = _052_ & _059_;
  assign _061_ = _044_ & _060_;
  assign _062_ = ~(pmode_state_reg[1] & _061_);
  assign _063_ = ~(pwr_budget_reg[9] & _046_);
  assign _064_ = ~(pwr_counters[9] & _053_);
  assign _065_ = _063_ & _064_;
  assign _066_ = ~(_062_ & _065_);
  assign _000_[9] = _047_ & _066_;
  assign _067_ = bus_cmd_addr[3] & _032_;
  assign _068_ = bus_cmd_addr[2] & _067_;
  assign _069_ = bus_cmd_addr[4] & _058_;
  assign _070_ = bus_cmd_addr[5] & _069_;
  assign _071_ = _044_ & _070_;
  assign _072_ = _068_ & _071_;
  assign _073_ = ~(bus_cmd_ready & _072_);
  assign _074_ = ~(pwr_counters[8] & _053_);
  assign _075_ = _073_ & _074_;
  assign _076_ = ~(pmode_state_reg[0] & _061_);
  assign _077_ = ~(pwr_budget_reg[8] & _046_);
  assign _078_ = _076_ & _077_;
  assign _079_ = ~(_075_ & _078_);
  assign _000_[8] = _047_ & _079_;
  assign _080_ = ~(pwr_budget_reg[7] & _046_);
  assign _081_ = ~(_034_ & _071_);
  assign _082_ = _073_ & _081_;
  assign _083_ = ~(_080_ & _082_);
  assign _000_[7] = _047_ & _083_;
  assign _084_ = ~(pwr_alert & _061_);
  assign _085_ = ~(pwr_counters[8] & _072_);
  assign _086_ = _084_ & _085_;
  assign _087_ = ~(pwr_budget_reg[6] & _046_);
  assign _088_ = _054_ & _081_;
  assign _089_ = _087_ & _088_;
  assign _090_ = ~(_086_ & _089_);
  assign _000_[6] = _047_ & _090_;
  assign _091_ = ~(pwr_budget_reg[5] & _046_);
  assign _092_ = ~(pwr_estimate[5] & _072_);
  assign _093_ = _088_ & _092_;
  assign _094_ = ~(_091_ & _093_);
  assign _000_[5] = _047_ & _094_;
  assign _095_ = _067_ & ~(bus_cmd_addr[2]);
  assign _096_ = _059_ & _095_;
  assign _097_ = _044_ & _096_;
  assign _098_ = ~(pmode_ack & _097_);
  assign _099_ = _034_ & _044_;
  assign _100_ = _059_ | _070_;
  assign _101_ = ~(_099_ & _100_);
  assign _102_ = ~(pwr_budget_reg[4] & _046_);
  assign _103_ = ~(pg_iso_en & _061_);
  assign _104_ = ~(pwr_estimate[4] & _072_);
  assign _105_ = _102_ & _103_;
  assign _106_ = _098_ & _104_;
  assign _107_ = _105_ & _106_;
  assign _108_ = ~(_101_ & _107_);
  assign _000_[4] = _047_ & _108_;
  assign _109_ = ~(pmode_state_reg[1] & _097_);
  assign _110_ = _101_ & _109_;
  assign _111_ = ~(pwr_budget_reg[3] & _046_);
  assign _112_ = _073_ & _111_;
  assign _113_ = ~(_110_ & _112_);
  assign _000_[3] = _047_ & _113_;
  assign _114_ = ~(pwr_estimate[2] & _072_);
  assign _115_ = _054_ & _101_;
  assign _116_ = _114_ & _115_;
  assign _117_ = ~(pm_error_reg & _061_);
  assign _118_ = ~(pwr_budget_reg[2] & _046_);
  assign _119_ = ~(pmode_state_reg[0] & _097_);
  assign _120_ = _118_ & _119_;
  assign _121_ = _117_ & _120_;
  assign _122_ = ~(_116_ & _121_);
  assign _000_[2] = _047_ & _122_;
  assign _123_ = ~(pmode_req[1] & _097_);
  assign _124_ = _101_ & _123_;
  assign _125_ = ~(pwr_budget_reg[1] & _046_);
  assign _126_ = ~(pwr_counters[9] & _072_);
  assign _127_ = ~(bus_cmd_ready & _061_);
  assign _128_ = _126_ & _127_;
  assign _129_ = _125_ & _128_;
  assign _130_ = ~(_124_ & _129_);
  assign _000_[1] = _047_ & _130_;
  assign _131_ = _081_ & _126_;
  assign _132_ = ~(pm_ready_reg & _061_);
  assign _133_ = ~(pmode_req[0] & _097_);
  assign _134_ = ~(pwr_budget_reg[0] & _046_);
  assign _135_ = _133_ & _134_;
  assign _136_ = _132_ & _135_;
  assign _137_ = ~(_131_ & _136_);
  assign _000_[0] = _047_ & _137_;
  assign _138_ = ~(pg_seq_state_reg[1] | pg_seq_state_reg[0]);
  assign _139_ = ~(pg_seq_state_reg[3] | pg_seq_state_reg[2]);
  assign _140_ = _138_ & ~(pg_seq_state_reg[2]);
  assign _141_ = ~(_138_ & _139_);
  assign _009_[0] = _027_ & _141_;
  assign _142_ = pg_seq_cnt_reg[1] & pg_seq_cnt_reg[0];
  assign _143_ = pg_seq_cnt_reg[2] & _142_;
  assign _144_ = pg_seq_cnt_reg[2] ^ _142_;
  assign _009_[2] = _141_ & _144_;
  assign _145_ = pg_seq_cnt_reg[1] ^ pg_seq_cnt_reg[0];
  assign _009_[1] = _141_ & _145_;
  assign _146_ = _138_ & ~(pg_seq_state_reg[3]);
  assign _147_ = pg_entering_reg | pg_seq_state_reg[2];
  assign _148_ = ~(_031_ & _138_);
  assign _149_ = _146_ & _147_;
  assign _010_[0] = _030_ | _149_;
  assign _150_ = pg_entering_reg | _141_;
  assign _151_ = pg_seq_state_reg[0] & ~(pg_seq_state_reg[1]);
  assign _152_ = ~(_139_ & _151_);
  assign _153_ = _030_ | ~(_152_);
  assign _010_[1] = _153_ | ~(_150_);
  assign _154_ = pg_seq_state_reg[1] & pg_seq_state_reg[0];
  assign _155_ = ~(_139_ & _154_);
  assign _019_ = ~(_007_ & _155_);
  assign _156_ = ~(_148_ & _150_);
  assign _010_[2] = _019_ | _156_;
  assign _283_[4] = activity_dram_sync_reg & activity_io_sync_reg;
  assign _285_[4] = activity_dram_sync_reg ^ activity_io_sync_reg;
  assign _157_ = dvfs_timeout_cnt_reg[3] | dvfs_timeout_cnt_reg[2];
  assign _158_ = dvfs_timeout_cnt_reg[4] | _157_;
  assign _159_ = dvfs_timeout_cnt_reg[5] & dvfs_timeout_cnt_reg[6];
  assign _160_ = _158_ & _159_;
  assign _161_ = ~(dvfs_timeout_cnt_reg[7] | _160_);
  assign _162_ = dvfs_timeout_cnt_reg[0] & _161_;
  assign _163_ = dvfs_timeout_cnt_reg[1] & _162_;
  assign _164_ = dvfs_timeout_cnt_reg[2] & _163_;
  assign _165_ = dvfs_timeout_cnt_reg[3] & _164_;
  assign _166_ = dvfs_timeout_cnt_reg[4] & _165_;
  assign _167_ = dvfs_timeout_cnt_reg[5] & _166_;
  assign _168_ = dvfs_timeout_cnt_reg[6] | _167_;
  assign _169_ = dvfs_state_reg[2] | dvfs_state_reg[0];
  assign _170_ = dvfs_op_ack | _169_;
  assign _171_ = vdd_main_ack | ~(dvfs_state_reg[2]);
  assign _172_ = ~(_170_ & _171_);
  assign _002_[6] = _168_ & _172_;
  assign _173_ = dvfs_timeout_cnt_reg[5] | _166_;
  assign _174_ = _172_ & _173_;
  assign _002_[5] = _174_ & ~(_167_);
  assign _175_ = dvfs_timeout_cnt_reg[3] ^ _164_;
  assign _002_[3] = _172_ & _175_;
  assign _176_ = dvfs_timeout_cnt_reg[4] ^ _165_;
  assign _002_[4] = _172_ & _176_;
  assign _177_ = dvfs_timeout_cnt_reg[2] ^ _163_;
  assign _002_[2] = _172_ & _177_;
  assign _178_ = dvfs_timeout_cnt_reg[1] ^ _162_;
  assign _002_[1] = _172_ & _178_;
  assign _179_ = dvfs_timeout_cnt_reg[0] ^ _161_;
  assign _002_[0] = _172_ & _179_;
  assign _005_ = pmode_state_reg[1] & pmode_state_reg[0];
  assign _003_ = ~_005_;
  assign _012_ = ~(pmode_state_reg[1] | pmode_state_reg[0]);
  assign _180_ = ~(_138_ | _154_);
  assign _021_ = _031_ & _180_;
  assign _181_ = pmode_state_reg[0] & pmode_req[1];
  assign _182_ = pmode_state_reg[0] | pmode_req[1];
  assign _025_ = ~(pmode_state_reg[1] & _182_);
  assign _183_ = _181_ | _025_;
  assign _184_ = pmode_state_reg[0] | ~(pmode_req[1]);
  assign _185_ = ~(pmode_req[0] & _184_);
  assign pmode_state_next[0] = ~(_183_ & _185_);
  assign _006_ = ~(pg_seq_state_reg[3] & _140_);
  assign _186_ = bus_cmd_valid & bus_cmd_rw;
  assign _187_ = rst_por_n & _186_;
  assign _024_ = _046_ & _187_;
  assign _188_ = _028_ & _005_;
  assign _189_ = pmode_req[1] | _188_;
  assign _190_ = pmode_state_reg[1] ? pmode_state_reg[0] : _028_;
  assign pmode_state_next[1] = _189_ & _190_;
  assign _002_[7] = dvfs_timeout_cnt_reg[7] & _172_;
  assign _004_ = pmode_state_reg[1] & ~(pmode_state_reg[0]);
  assign _022_ = ~(_152_ & _006_);
  assign _191_ = _029_ & _139_;
  assign _192_ = pg_seq_cnt_reg[2] | pg_seq_cnt_reg[1];
  assign _193_ = ~(pg_seq_cnt_reg[3] & _192_);
  assign _194_ = ~(_191_ & _193_);
  assign _010_[3] = _031_ & _154_;
  assign _195_ = _146_ | ~(_152_);
  assign _196_ = ~(_010_[3] | _195_);
  assign _026_ = ~(_194_ & _196_);
  assign _197_ = _070_ & _095_;
  assign _198_ = _197_ | ~(_186_);
  assign _199_ = ~(_060_ | _096_);
  assign _200_ = _069_ & ~(bus_cmd_addr[5]);
  assign _201_ = ~(_034_ & _200_);
  assign _202_ = ~(_052_ & _070_);
  assign _203_ = ~(_037_ & _068_);
  assign _204_ = _202_ & _203_;
  assign _205_ = _201_ & _204_;
  assign _206_ = ~(_199_ & _205_);
  assign _207_ = ~(_198_ & _206_);
  assign _208_ = _037_ | _070_;
  assign _209_ = bus_cmd_addr[2] ? _067_ : _033_;
  assign _210_ = ~(_059_ & _209_);
  assign _211_ = ~(_034_ & _208_);
  assign _212_ = _210_ & _211_;
  assign _213_ = ~(_207_ & _212_);
  assign _214_ = ~(_044_ & _213_);
  assign _215_ = ~(_044_ & _197_);
  assign _216_ = ~(_186_ & _215_);
  assign _217_ = ~(_047_ & _054_);
  assign _218_ = _072_ | _217_;
  assign _219_ = ~(_216_ & _218_);
  assign _001_ = _214_ & _219_;
  assign _220_ = pwr_budget_reg[15] & _047_;
  assign _000_[15] = _046_ & _220_;
  assign _221_ = ~(pg_seq_cnt_reg[3] & _143_);
  assign _222_ = pg_seq_cnt_reg[3] ^ _143_;
  assign _009_[3] = _141_ & _222_;
  assign _011_ = vdd_main_error | ~(_161_);
  assign _223_ = _161_ & ~(dvfs_op_ack);
  assign _014_ = dvfs_state_reg[1] & _223_;
  assign _224_ = ~(dvfs_state_reg[3] & vdd_main_ready);
  assign _225_ = _161_ & ~(vdd_main_ack);
  assign _226_ = ~(dvfs_state_reg[2] & _225_);
  assign _017_ = ~(_224_ & _226_);
  assign _016_ = dvfs_state_reg[0] | dvfs_state_reg[4];
  assign _227_ = pg_exiting_reg | _150_;
  assign _228_ = _194_ & _227_;
  assign _229_ = ~(pg_main_status & _148_);
  assign _230_ = pg_main_status | _010_[3];
  assign _231_ = _221_ & _230_;
  assign _232_ = ~(_229_ & _231_);
  assign _023_ = _228_ & _232_;
  assign _020_ = dvfs_state_reg[1] | _169_;
  assign _015_ = dvfs_state_reg[2] & ~(_225_);
  assign _233_ = pwr_budget_reg[8] | ~(bus_cmd_ready);
  assign _234_ = bus_cmd_ready | ~(pwr_budget_reg[7]);
  assign _235_ = pwr_budget_reg[7] | ~(bus_cmd_ready);
  assign _236_ = _234_ & _235_;
  assign _237_ = pwr_counters[8] & ~(pwr_budget_reg[6]);
  assign _238_ = ~(pwr_budget_reg[6] ^ pwr_counters[8]);
  assign _239_ = _236_ & _238_;
  assign _240_ = pwr_estimate[5] | ~(pwr_budget_reg[5]);
  assign _241_ = pwr_budget_reg[5] | ~(pwr_estimate[5]);
  assign _242_ = pwr_budget_reg[4] | ~(pwr_estimate[4]);
  assign _243_ = ~(_241_ & _242_);
  assign _244_ = ~(_240_ & _243_);
  assign _245_ = bus_cmd_ready | ~(pwr_budget_reg[3]);
  assign _246_ = pwr_estimate[4] | ~(pwr_budget_reg[4]);
  assign _247_ = _240_ & _246_;
  assign _248_ = ~(_245_ & _247_);
  assign _249_ = ~(_243_ | _248_);
  assign _250_ = ~(pwr_budget_reg[1] | pwr_budget_reg[0]);
  assign _251_ = pwr_counters[9] | _250_;
  assign _252_ = pwr_budget_reg[3] | ~(bus_cmd_ready);
  assign _253_ = pwr_estimate[2] | ~(pwr_budget_reg[2]);
  assign _254_ = _252_ & _253_;
  assign _255_ = ~(_251_ & _254_);
  assign _256_ = pwr_budget_reg[2] | ~(pwr_estimate[2]);
  assign _257_ = _252_ & _256_;
  assign _258_ = ~(_255_ & _257_);
  assign _259_ = ~(_249_ & _258_);
  assign _260_ = ~(_244_ & _259_);
  assign _261_ = ~(_239_ & _260_);
  assign _262_ = ~(_234_ & _237_);
  assign _263_ = _235_ & _262_;
  assign _264_ = ~(_261_ & _263_);
  assign _265_ = bus_cmd_ready | ~(pwr_budget_reg[8]);
  assign _266_ = ~(pwr_budget_reg[1] & pwr_budget_reg[0]);
  assign _267_ = ~(pwr_counters[9] & _266_);
  assign _268_ = _256_ & _267_;
  assign _269_ = _239_ & _268_;
  assign _270_ = ~(_249_ & _269_);
  assign _271_ = ~(_255_ | _270_);
  assign _272_ = _265_ & ~(_271_);
  assign _273_ = ~(_264_ & _272_);
  assign _274_ = ~(_233_ & _273_);
  assign _275_ = ~(pwr_budget_reg[15] | pwr_budget_reg[14]);
  assign _276_ = _275_ & ~(pwr_budget_reg[13]);
  assign _277_ = ~(pwr_budget_reg[12] | pwr_budget_reg[11]);
  assign _278_ = ~(pwr_budget_reg[10] | pwr_budget_reg[9]);
  assign _279_ = _277_ & _278_;
  assign _280_ = _276_ & _279_;
  assign _013_ = _274_ & _280_;
  assign _281_ = _223_ | ~(dvfs_state_reg[1]);
  assign _282_ = vdd_main_ready | ~(dvfs_state_reg[3]);
  assign _018_ = ~(_281_ & _282_);
  always @(posedge clk_aon)
    if (rst_por_n) pg_iso_en <= pmode_state_reg[1];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pg_iso_en <= 1'h0;
    else if (_022_) pg_iso_en <= _006_;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pg_seq_cnt_reg[0] <= 1'h0;
    else if (_026_) pg_seq_cnt_reg[0] <= _009_[0];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pg_seq_cnt_reg[1] <= 1'h0;
    else if (_026_) pg_seq_cnt_reg[1] <= _009_[1];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pg_seq_cnt_reg[2] <= 1'h0;
    else if (_026_) pg_seq_cnt_reg[2] <= _009_[2];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pg_seq_cnt_reg[3] <= 1'h0;
    else if (_026_) pg_seq_cnt_reg[3] <= _009_[3];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pg_iso_en <= 1'h0;
    else if (_021_) pg_iso_en <= _007_;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pmode_state_reg[0] <= 1'h1;
    else if (_025_) pmode_state_reg[0] <= pmode_state_next[0];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pmode_state_reg[1] <= 1'h1;
    else if (_025_) pmode_state_reg[1] <= pmode_state_next[1];
  always @(posedge clk_aon)
    if (_024_) pwr_budget_reg[0] <= bus_cmd_data[0];
  always @(posedge clk_aon)
    if (_024_) pwr_budget_reg[1] <= bus_cmd_data[1];
  always @(posedge clk_aon)
    if (_024_) pwr_budget_reg[2] <= bus_cmd_data[2];
  always @(posedge clk_aon)
    if (_024_) pwr_budget_reg[3] <= bus_cmd_data[3];
  always @(posedge clk_aon)
    if (_024_) pwr_budget_reg[4] <= bus_cmd_data[4];
  always @(posedge clk_aon)
    if (_024_) pwr_budget_reg[5] <= bus_cmd_data[5];
  always @(posedge clk_aon)
    if (_024_) pwr_budget_reg[6] <= bus_cmd_data[6];
  always @(posedge clk_aon)
    if (_024_) pwr_budget_reg[7] <= bus_cmd_data[7];
  always @(posedge clk_aon)
    if (_024_) pwr_budget_reg[8] <= bus_cmd_data[8];
  always @(posedge clk_aon)
    if (_024_) pwr_budget_reg[9] <= bus_cmd_data[9];
  always @(posedge clk_aon)
    if (_024_) pwr_budget_reg[10] <= bus_cmd_data[10];
  always @(posedge clk_aon)
    if (_024_) pwr_budget_reg[11] <= bus_cmd_data[11];
  always @(posedge clk_aon)
    if (_024_) pwr_budget_reg[12] <= bus_cmd_data[12];
  always @(posedge clk_aon)
    if (_024_) pwr_budget_reg[13] <= bus_cmd_data[13];
  always @(posedge clk_aon)
    if (_024_) pwr_budget_reg[14] <= bus_cmd_data[14];
  always @(posedge clk_aon)
    if (_024_) pwr_budget_reg[15] <= bus_cmd_data[15];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) dvfs_timeout_cnt_reg[0] <= 1'h0;
    else if (_020_) dvfs_timeout_cnt_reg[0] <= _002_[0];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) dvfs_timeout_cnt_reg[1] <= 1'h0;
    else if (_020_) dvfs_timeout_cnt_reg[1] <= _002_[1];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) dvfs_timeout_cnt_reg[2] <= 1'h0;
    else if (_020_) dvfs_timeout_cnt_reg[2] <= _002_[2];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) dvfs_timeout_cnt_reg[3] <= 1'h0;
    else if (_020_) dvfs_timeout_cnt_reg[3] <= _002_[3];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) dvfs_timeout_cnt_reg[4] <= 1'h0;
    else if (_020_) dvfs_timeout_cnt_reg[4] <= _002_[4];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) dvfs_timeout_cnt_reg[5] <= 1'h0;
    else if (_020_) dvfs_timeout_cnt_reg[5] <= _002_[5];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) dvfs_timeout_cnt_reg[6] <= 1'h0;
    else if (_020_) dvfs_timeout_cnt_reg[6] <= _002_[6];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) dvfs_timeout_cnt_reg[7] <= 1'h0;
    else if (_020_) dvfs_timeout_cnt_reg[7] <= _002_[7];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pg_seq_state_reg[0] <= 1'h0;
    else if (_023_) pg_seq_state_reg[0] <= _010_[0];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pg_seq_state_reg[1] <= 1'h0;
    else if (_023_) pg_seq_state_reg[1] <= _010_[1];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pg_seq_state_reg[2] <= 1'h0;
    else if (_023_) pg_seq_state_reg[2] <= _010_[2];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pg_seq_state_reg[3] <= 1'h0;
    else if (_023_) pg_seq_state_reg[3] <= _010_[3];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pg_main_switch <= 1'h1;
    else if (_019_) pg_main_switch <= _008_;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) dvfs_state_reg[0] <= 1'h1;
    else dvfs_state_reg[0] <= _016_;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) dvfs_state_reg[1] <= 1'h0;
    else dvfs_state_reg[1] <= _014_;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) dvfs_state_reg[2] <= 1'h0;
    else dvfs_state_reg[2] <= _017_;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) dvfs_state_reg[3] <= 1'h0;
    else dvfs_state_reg[3] <= _018_;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) dvfs_state_reg[4] <= 1'h0;
    else dvfs_state_reg[4] <= _015_;
  reg \pwr_counters_reg[10] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \pwr_counters_reg[10]  <= 1'h0;
    else \pwr_counters_reg[10]  <= activity_main_sync_reg;
  assign pwr_counters[10] = \pwr_counters_reg[10] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) bus_rsp_valid <= 1'h0;
    else bus_rsp_valid <= bus_cmd_valid;
  reg \bus_rsp_data_reg[0] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \bus_rsp_data_reg[0]  <= 1'h0;
    else \bus_rsp_data_reg[0]  <= _000_[0];
  assign bus_rsp_data[0] = \bus_rsp_data_reg[0] ;
  reg \bus_rsp_data_reg[1] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \bus_rsp_data_reg[1]  <= 1'h0;
    else \bus_rsp_data_reg[1]  <= _000_[1];
  assign bus_rsp_data[1] = \bus_rsp_data_reg[1] ;
  reg \bus_rsp_data_reg[2] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \bus_rsp_data_reg[2]  <= 1'h0;
    else \bus_rsp_data_reg[2]  <= _000_[2];
  assign bus_rsp_data[2] = \bus_rsp_data_reg[2] ;
  reg \bus_rsp_data_reg[3] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \bus_rsp_data_reg[3]  <= 1'h0;
    else \bus_rsp_data_reg[3]  <= _000_[3];
  assign bus_rsp_data[3] = \bus_rsp_data_reg[3] ;
  reg \bus_rsp_data_reg[4] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \bus_rsp_data_reg[4]  <= 1'h0;
    else \bus_rsp_data_reg[4]  <= _000_[4];
  assign bus_rsp_data[4] = \bus_rsp_data_reg[4] ;
  reg \bus_rsp_data_reg[5] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \bus_rsp_data_reg[5]  <= 1'h0;
    else \bus_rsp_data_reg[5]  <= _000_[5];
  assign bus_rsp_data[5] = \bus_rsp_data_reg[5] ;
  reg \bus_rsp_data_reg[6] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \bus_rsp_data_reg[6]  <= 1'h0;
    else \bus_rsp_data_reg[6]  <= _000_[6];
  assign bus_rsp_data[6] = \bus_rsp_data_reg[6] ;
  reg \bus_rsp_data_reg[7] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \bus_rsp_data_reg[7]  <= 1'h0;
    else \bus_rsp_data_reg[7]  <= _000_[7];
  assign bus_rsp_data[7] = \bus_rsp_data_reg[7] ;
  reg \bus_rsp_data_reg[8] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \bus_rsp_data_reg[8]  <= 1'h0;
    else \bus_rsp_data_reg[8]  <= _000_[8];
  assign bus_rsp_data[8] = \bus_rsp_data_reg[8] ;
  reg \bus_rsp_data_reg[9] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \bus_rsp_data_reg[9]  <= 1'h0;
    else \bus_rsp_data_reg[9]  <= _000_[9];
  assign bus_rsp_data[9] = \bus_rsp_data_reg[9] ;
  reg \bus_rsp_data_reg[10] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \bus_rsp_data_reg[10]  <= 1'h0;
    else \bus_rsp_data_reg[10]  <= _000_[10];
  assign bus_rsp_data[10] = \bus_rsp_data_reg[10] ;
  reg \bus_rsp_data_reg[11] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \bus_rsp_data_reg[11]  <= 1'h0;
    else \bus_rsp_data_reg[11]  <= _000_[11];
  assign bus_rsp_data[11] = \bus_rsp_data_reg[11] ;
  reg \bus_rsp_data_reg[12] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \bus_rsp_data_reg[12]  <= 1'h0;
    else \bus_rsp_data_reg[12]  <= _000_[12];
  assign bus_rsp_data[12] = \bus_rsp_data_reg[12] ;
  reg \bus_rsp_data_reg[13] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \bus_rsp_data_reg[13]  <= 1'h0;
    else \bus_rsp_data_reg[13]  <= _000_[13];
  assign bus_rsp_data[13] = \bus_rsp_data_reg[13] ;
  reg \bus_rsp_data_reg[14] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \bus_rsp_data_reg[14]  <= 1'h0;
    else \bus_rsp_data_reg[14]  <= _000_[14];
  assign bus_rsp_data[14] = \bus_rsp_data_reg[14] ;
  reg \bus_rsp_data_reg[15] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \bus_rsp_data_reg[15]  <= 1'h0;
    else \bus_rsp_data_reg[15]  <= _000_[15];
  assign bus_rsp_data[15] = \bus_rsp_data_reg[15] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) bus_rsp_error <= 1'h0;
    else bus_rsp_error <= _001_;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pm_ready_reg <= 1'h0;
    else pm_ready_reg <= _012_;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pm_error_reg <= 1'h0;
    else pm_error_reg <= _011_;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pmode_state[0] <= 1'h1;
    else pmode_state[0] <= pmode_state_reg[0];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pmode_state[1] <= 1'h1;
    else pmode_state[1] <= pmode_state_reg[1];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pg_entering_reg <= 1'h0;
    else pg_entering_reg <= _004_;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pg_exiting_reg <= 1'h0;
    else pg_exiting_reg <= _005_;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pmode_ack <= 1'h0;
    else pmode_ack <= _003_;
  reg \pwr_counters_reg[9] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \pwr_counters_reg[9]  <= 1'h0;
    else \pwr_counters_reg[9]  <= activity_io_sync_reg;
  assign pwr_counters[9] = \pwr_counters_reg[9] ;
  reg \pwr_estimate_reg[2] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \pwr_estimate_reg[2]  <= 1'h0;
    else \pwr_estimate_reg[2]  <= _284_[2];
  assign pwr_estimate[2] = \pwr_estimate_reg[2] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) bus_cmd_ready <= 1'h0;
    else bus_cmd_ready <= 1'h1;
  reg \pwr_estimate_reg[4] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \pwr_estimate_reg[4]  <= 1'h0;
    else \pwr_estimate_reg[4]  <= _285_[4];
  assign pwr_estimate[4] = \pwr_estimate_reg[4] ;
  reg \pwr_estimate_reg[5] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \pwr_estimate_reg[5]  <= 1'h0;
    else \pwr_estimate_reg[5]  <= _283_[4];
  assign pwr_estimate[5] = \pwr_estimate_reg[5] ;
  reg \pwr_counters_reg[8] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) \pwr_counters_reg[8]  <= 1'h0;
    else \pwr_counters_reg[8]  <= activity_dram_sync_reg;
  assign pwr_counters[8] = \pwr_counters_reg[8] ;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pwr_budget_reg[0] <= 1'h0;
    else pwr_budget_reg[0] <= pwr_budget[0];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pwr_budget_reg[1] <= 1'h0;
    else pwr_budget_reg[1] <= pwr_budget[1];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pwr_budget_reg[2] <= 1'h0;
    else pwr_budget_reg[2] <= pwr_budget[2];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pwr_budget_reg[3] <= 1'h0;
    else pwr_budget_reg[3] <= pwr_budget[3];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pwr_budget_reg[4] <= 1'h0;
    else pwr_budget_reg[4] <= pwr_budget[4];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pwr_budget_reg[5] <= 1'h0;
    else pwr_budget_reg[5] <= pwr_budget[5];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pwr_budget_reg[6] <= 1'h0;
    else pwr_budget_reg[6] <= pwr_budget[6];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pwr_budget_reg[7] <= 1'h0;
    else pwr_budget_reg[7] <= pwr_budget[7];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pwr_budget_reg[8] <= 1'h1;
    else pwr_budget_reg[8] <= pwr_budget[8];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pwr_budget_reg[9] <= 1'h1;
    else pwr_budget_reg[9] <= pwr_budget[9];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pwr_budget_reg[10] <= 1'h1;
    else pwr_budget_reg[10] <= pwr_budget[10];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pwr_budget_reg[11] <= 1'h0;
    else pwr_budget_reg[11] <= pwr_budget[11];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pwr_budget_reg[12] <= 1'h0;
    else pwr_budget_reg[12] <= pwr_budget[12];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pwr_budget_reg[13] <= 1'h0;
    else pwr_budget_reg[13] <= pwr_budget[13];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pwr_budget_reg[14] <= 1'h0;
    else pwr_budget_reg[14] <= pwr_budget[14];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pwr_budget_reg[15] <= 1'h0;
    else pwr_budget_reg[15] <= pwr_budget[15];
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) pwr_alert <= 1'h0;
    else pwr_alert <= _013_;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) activity_main_sync_reg <= 1'h0;
    else activity_main_sync_reg <= activity_main_stage1;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) activity_io_sync_reg <= 1'h0;
    else activity_io_sync_reg <= activity_io_stage1;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) activity_dram_sync_reg <= 1'h0;
    else activity_dram_sync_reg <= activity_dram_stage1;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) activity_main_stage0 <= 1'h0;
    else activity_main_stage0 <= activity_main;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) activity_main_stage1 <= 1'h0;
    else activity_main_stage1 <= activity_main_stage0;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) activity_io_stage0 <= 1'h0;
    else activity_io_stage0 <= activity_io;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) activity_io_stage1 <= 1'h0;
    else activity_io_stage1 <= activity_io_stage0;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) activity_dram_stage0 <= 1'h0;
    else activity_dram_stage0 <= activity_dram;
  always @(posedge clk_aon, negedge rst_por_n)
    if (!rst_por_n) activity_dram_stage1 <= 1'h0;
    else activity_dram_stage1 <= activity_dram_stage0;
  assign { _284_[11:3], _284_[1:0] } = { 5'h03, activity_dram_sync_reg, 1'h0, activity_dram_sync_reg, _284_[2], activity_io_sync_reg, activity_io_sync_reg };
  assign { _285_[11:5], _285_[3:0] } = { 5'h03, activity_dram_sync_reg, _283_[4], 1'h1, _284_[2], activity_io_sync_reg, activity_io_sync_reg };
  assign { _283_[11:5], _283_[3:0] } = { 7'h00, activity_io_sync_reg, activity_io_sync_reg, 2'h0 };
  assign pm_irq_type = 3'h0;
  assign pm_irq = 1'h0;
  assign pm_status = { pm_error_reg, bus_cmd_ready, pm_ready_reg, 1'h0, pg_iso_en, 1'h0, pwr_alert, 1'h0 };
  assign idle_detected = 1'h0;
  assign { pwr_counters[31:11], pwr_counters[7:0] } = 29'h00000064;
  assign { pwr_estimate[15:6], pwr_estimate[3], pwr_estimate[1:0] } = { 7'h00, bus_cmd_ready, bus_cmd_ready, pwr_counters[8], bus_cmd_ready, pwr_counters[9], pwr_counters[9] };
  assign wakeup_pending = 1'h0;
  assign wakeup_status = 8'h00;
  assign wakeup_en = 8'hff;
  assign pmode_error = 1'h0;
  assign pg_main_en = pg_iso_en;
  assign vdd_main_set = 8'h12;
  assign dvfs_freq_req = 32'd500;
  assign dvfs_vdd_req = 3'h0;
  assign dvfs_op_req = 2'h0;
  assign bus_rsp_data[31:16] = 16'h0000;
endmodule
