/* Generated by Yosys 0.65+37 (git sha1 e87a9bd9a, clang++ 18.1.8 -fPIC -O3) */

module M06_ClockManager(ext_clk_i, pll_lock_i, dvfs_op_i, dvfs_req_i, clk_gating_en_i, pd_aon_vdd_i, clk_sys_o, clk_aon_o, clk_io_o, clk_gating_o, dvfs_ack_o, clk_status_o, pll_pwr_en_o);
  input ext_clk_i;
  wire ext_clk_i;
  input pll_lock_i;
  wire pll_lock_i;
  input [1:0] dvfs_op_i;
  wire [1:0] dvfs_op_i;
  input dvfs_req_i;
  wire dvfs_req_i;
  input [13:0] clk_gating_en_i;
  wire [13:0] clk_gating_en_i;
  input pd_aon_vdd_i;
  wire pd_aon_vdd_i;
  output clk_sys_o;
  wire clk_sys_o;
  output clk_aon_o;
  reg clk_aon_o;
  output clk_io_o;
  wire clk_io_o;
  output [13:0] clk_gating_o;
  reg [13:0] clk_gating_o;
  output dvfs_ack_o;
  reg dvfs_ack_o;
  output [2:0] clk_status_o;
  wire [2:0] clk_status_o;
  output pll_pwr_en_o;
  wire pll_pwr_en_o;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire [5:0] _137_;
  wire [5:0] _138_;
  reg aon_clk_pulse;
  reg [5:0] aon_div_counter;
  reg [13:0] clk_gating_sync;
  wire [6:0] current_state;
  reg dvfs_req_prev;
  reg [15:0] timeout_counter;
  assign _095_ = ~timeout_counter[0];
  assign _137_[0] = ~aon_div_counter[0];
  assign _096_ = ~current_state[1];
  assign _120_ = ~clk_aon_o;
  assign _097_ = aon_div_counter[0] & ~(aon_div_counter[1]);
  assign _138_[1] = aon_div_counter[1] ^ aon_div_counter[0];
  assign _098_ = timeout_counter[0] & timeout_counter[1];
  assign _099_ = timeout_counter[2] & _098_;
  assign _100_ = timeout_counter[3] & _099_;
  assign _101_ = timeout_counter[4] & _100_;
  assign _102_ = timeout_counter[5] & timeout_counter[6];
  assign _103_ = _101_ & _102_;
  assign _104_ = timeout_counter[7] & _103_;
  assign _105_ = timeout_counter[8] & _104_;
  assign _106_ = timeout_counter[9] & _105_;
  assign _107_ = timeout_counter[10] & _106_;
  assign _108_ = timeout_counter[11] & _107_;
  assign _109_ = timeout_counter[12] & _108_;
  assign _110_ = timeout_counter[13] & _109_;
  assign _111_ = ~(timeout_counter[14] & _110_);
  assign _112_ = current_state[5] | current_state[1];
  assign _113_ = current_state[2] | _112_;
  assign _114_ = timeout_counter[5] & _101_;
  assign _115_ = timeout_counter[6] & _114_;
  assign _116_ = timeout_counter[7] & _115_;
  assign _117_ = timeout_counter[8] & _116_;
  assign _118_ = timeout_counter[9] & _117_;
  assign _119_ = timeout_counter[10] & _118_;
  assign _009_ = timeout_counter[11] & _119_;
  assign _010_ = timeout_counter[12] & _009_;
  assign _011_ = timeout_counter[14] | _110_;
  assign _012_ = _113_ & _011_;
  assign _126_ = _111_ & _012_;
  assign _013_ = timeout_counter[13] ^ _010_;
  assign _125_ = _113_ & _013_;
  assign _014_ = timeout_counter[12] ^ _009_;
  assign _124_ = _113_ & _014_;
  assign _015_ = timeout_counter[11] ^ _119_;
  assign _123_ = _113_ & _015_;
  assign _016_ = timeout_counter[10] ^ _118_;
  assign _122_ = _113_ & _016_;
  assign _017_ = timeout_counter[9] ^ _117_;
  assign _136_ = _113_ & _017_;
  assign _018_ = timeout_counter[8] ^ _116_;
  assign _135_ = _113_ & _018_;
  assign _019_ = timeout_counter[7] ^ _115_;
  assign _134_ = _113_ & _019_;
  assign _020_ = timeout_counter[6] ^ _114_;
  assign _133_ = _113_ & _020_;
  assign _021_ = timeout_counter[5] | _101_;
  assign _022_ = _113_ & _021_;
  assign _132_ = _022_ & ~(_114_);
  assign _023_ = timeout_counter[4] ^ _100_;
  assign _131_ = _113_ & _023_;
  assign _024_ = timeout_counter[3] ^ _099_;
  assign _130_ = _113_ & _024_;
  assign _025_ = timeout_counter[2] ^ _098_;
  assign _129_ = _113_ & _025_;
  assign _026_ = timeout_counter[0] | timeout_counter[1];
  assign _027_ = _113_ & _026_;
  assign _128_ = _027_ & ~(_098_);
  assign _121_ = _095_ & _113_;
  assign clk_status_o[0] = current_state[3] | _113_;
  assign _028_ = aon_div_counter[1] & aon_div_counter[0];
  assign _029_ = aon_div_counter[2] & _028_;
  assign _138_[2] = aon_div_counter[2] ^ _028_;
  assign _030_ = aon_div_counter[3] & _029_;
  assign _138_[3] = aon_div_counter[3] ^ _029_;
  assign _031_ = ~(timeout_counter[10] | timeout_counter[9]);
  assign _032_ = ~(timeout_counter[8] | timeout_counter[13]);
  assign _033_ = ~(timeout_counter[5] | timeout_counter[4]);
  assign _034_ = ~(timeout_counter[11] | timeout_counter[12]);
  assign _035_ = _031_ & _034_;
  assign _036_ = _032_ & ~(timeout_counter[15]);
  assign _037_ = _035_ & _036_;
  assign _038_ = _037_ & ~(timeout_counter[14]);
  assign _039_ = ~(timeout_counter[6] | timeout_counter[7]);
  assign _040_ = _033_ & _039_;
  assign _041_ = _038_ & _040_;
  assign _042_ = _041_ & ~(timeout_counter[3]);
  assign _043_ = ~(timeout_counter[2] & _026_);
  assign _044_ = ~(_042_ & _043_);
  assign _045_ = ~(current_state[1] & _044_);
  assign _046_ = timeout_counter[3] | timeout_counter[2];
  assign _047_ = timeout_counter[4] | _046_;
  assign _048_ = ~(_102_ & _047_);
  assign _049_ = ~(_038_ & _048_);
  assign _050_ = timeout_counter[7] | _049_;
  assign _051_ = ~(current_state[5] & _050_);
  assign _052_ = timeout_counter[2] | timeout_counter[1];
  assign _053_ = ~(timeout_counter[3] & _052_);
  assign _054_ = ~(_041_ & _053_);
  assign _055_ = ~(current_state[2] & _054_);
  assign _056_ = _051_ & _055_;
  assign _008_ = _045_ & _056_;
  assign _057_ = current_state[5] & pd_aon_vdd_i;
  assign _058_ = _057_ & ~(pll_lock_i);
  assign _059_ = ~(_008_ & _058_);
  assign _060_ = ~(timeout_counter[2] | _026_);
  assign _061_ = _042_ & _060_;
  assign _062_ = ~(_042_ & _060_);
  assign _063_ = current_state[2] & pd_aon_vdd_i;
  assign _064_ = ~(_062_ & _063_);
  assign _006_ = ~(_059_ & _064_);
  assign _065_ = ~(dvfs_ack_o & _061_);
  assign _066_ = ~(_045_ & _065_);
  assign _005_ = pd_aon_vdd_i & _066_;
  assign _067_ = dvfs_req_i & ~(dvfs_req_prev);
  assign _068_ = ~(dvfs_op_i[0] & dvfs_op_i[1]);
  assign _069_ = pll_lock_i & _068_;
  assign _070_ = _067_ & _069_;
  assign _071_ = pd_aon_vdd_i & current_state[0];
  assign _001_ = _070_ & _071_;
  assign _072_ = current_state[3] & pd_aon_vdd_i;
  assign _073_ = ~(_068_ & _072_);
  assign _074_ = ~(_061_ & _063_);
  assign _004_ = ~(_073_ & _074_);
  assign _075_ = ~(current_state[5] & pll_lock_i);
  assign _076_ = _096_ | _044_;
  assign _077_ = ~(_075_ & _076_);
  assign _003_ = pd_aon_vdd_i & _077_;
  assign _078_ = ~(dvfs_ack_o & _062_);
  assign _079_ = _067_ & ~(pll_lock_i);
  assign _080_ = _071_ & ~(_079_);
  assign _081_ = _080_ & ~(_070_);
  assign _082_ = pd_aon_vdd_i & ~(clk_status_o[2]);
  assign _083_ = _082_ & ~(_081_);
  assign _002_ = ~(_078_ & _083_);
  assign _084_ = dvfs_ack_o | current_state[0];
  assign _085_ = clk_status_o[0] | _084_;
  assign pll_pwr_en_o = pd_aon_vdd_i & _085_;
  assign _086_ = _008_ | ~(_058_);
  assign _087_ = _068_ | ~(_072_);
  assign _088_ = ~(_071_ & _079_);
  assign _089_ = _087_ & _088_;
  assign _007_ = ~(_086_ & _089_);
  assign _090_ = ~(timeout_counter[15] ^ _111_);
  assign _127_ = _113_ & _090_;
  assign _091_ = ~(aon_div_counter[4] & _030_);
  assign _138_[5] = ~(aon_div_counter[5] ^ _091_);
  assign _092_ = aon_div_counter[4] & ~(aon_div_counter[2]);
  assign _093_ = aon_div_counter[5] & ~(aon_div_counter[3]);
  assign _094_ = _097_ & _093_;
  assign _000_ = _092_ & _094_;
  assign _138_[4] = aon_div_counter[4] ^ _030_;
  always @(posedge ext_clk_i)
    aon_clk_pulse <= _000_;
  always @(posedge ext_clk_i)
    if (_000_) aon_div_counter[0] <= 1'h0;
    else aon_div_counter[0] <= _137_[0];
  always @(posedge ext_clk_i)
    if (_000_) aon_div_counter[1] <= 1'h0;
    else aon_div_counter[1] <= _138_[1];
  always @(posedge ext_clk_i)
    if (_000_) aon_div_counter[2] <= 1'h0;
    else aon_div_counter[2] <= _138_[2];
  always @(posedge ext_clk_i)
    if (_000_) aon_div_counter[3] <= 1'h0;
    else aon_div_counter[3] <= _138_[3];
  always @(posedge ext_clk_i)
    if (_000_) aon_div_counter[4] <= 1'h0;
    else aon_div_counter[4] <= _138_[4];
  always @(posedge ext_clk_i)
    if (_000_) aon_div_counter[5] <= 1'h0;
    else aon_div_counter[5] <= _138_[5];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_o[0] <= 1'h0;
    else clk_gating_o[0] <= clk_gating_sync[0];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_o[1] <= 1'h0;
    else clk_gating_o[1] <= clk_gating_sync[1];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_o[2] <= 1'h0;
    else clk_gating_o[2] <= clk_gating_sync[2];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_o[3] <= 1'h0;
    else clk_gating_o[3] <= clk_gating_sync[3];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_o[4] <= 1'h0;
    else clk_gating_o[4] <= clk_gating_sync[4];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_o[5] <= 1'h0;
    else clk_gating_o[5] <= clk_gating_sync[5];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_o[6] <= 1'h0;
    else clk_gating_o[6] <= clk_gating_sync[6];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_o[7] <= 1'h0;
    else clk_gating_o[7] <= clk_gating_sync[7];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_o[8] <= 1'h0;
    else clk_gating_o[8] <= clk_gating_sync[8];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_o[9] <= 1'h0;
    else clk_gating_o[9] <= clk_gating_sync[9];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_o[10] <= 1'h0;
    else clk_gating_o[10] <= clk_gating_sync[10];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_o[11] <= 1'h0;
    else clk_gating_o[11] <= clk_gating_sync[11];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_o[12] <= 1'h0;
    else clk_gating_o[12] <= clk_gating_sync[12];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_o[13] <= 1'h0;
    else clk_gating_o[13] <= clk_gating_sync[13];
  always @(posedge ext_clk_i)
    if (aon_clk_pulse) clk_aon_o <= _120_;
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_sync[0] <= 1'h0;
    else clk_gating_sync[0] <= clk_gating_en_i[0];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_sync[1] <= 1'h0;
    else clk_gating_sync[1] <= clk_gating_en_i[1];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_sync[2] <= 1'h0;
    else clk_gating_sync[2] <= clk_gating_en_i[2];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_sync[3] <= 1'h0;
    else clk_gating_sync[3] <= clk_gating_en_i[3];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_sync[4] <= 1'h0;
    else clk_gating_sync[4] <= clk_gating_en_i[4];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_sync[5] <= 1'h0;
    else clk_gating_sync[5] <= clk_gating_en_i[5];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_sync[6] <= 1'h0;
    else clk_gating_sync[6] <= clk_gating_en_i[6];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_sync[7] <= 1'h0;
    else clk_gating_sync[7] <= clk_gating_en_i[7];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_sync[8] <= 1'h0;
    else clk_gating_sync[8] <= clk_gating_en_i[8];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_sync[9] <= 1'h0;
    else clk_gating_sync[9] <= clk_gating_en_i[9];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_sync[10] <= 1'h0;
    else clk_gating_sync[10] <= clk_gating_en_i[10];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_sync[11] <= 1'h0;
    else clk_gating_sync[11] <= clk_gating_en_i[11];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_sync[12] <= 1'h0;
    else clk_gating_sync[12] <= clk_gating_en_i[12];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) clk_gating_sync[13] <= 1'h0;
    else clk_gating_sync[13] <= clk_gating_en_i[13];
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) timeout_counter[0] <= 1'h0;
    else if (_008_) timeout_counter[0] <= _121_;
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) timeout_counter[1] <= 1'h0;
    else if (_008_) timeout_counter[1] <= _128_;
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) timeout_counter[2] <= 1'h0;
    else if (_008_) timeout_counter[2] <= _129_;
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) timeout_counter[3] <= 1'h0;
    else if (_008_) timeout_counter[3] <= _130_;
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) timeout_counter[4] <= 1'h0;
    else if (_008_) timeout_counter[4] <= _131_;
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) timeout_counter[5] <= 1'h0;
    else if (_008_) timeout_counter[5] <= _132_;
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) timeout_counter[6] <= 1'h0;
    else if (_008_) timeout_counter[6] <= _133_;
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) timeout_counter[7] <= 1'h0;
    else if (_008_) timeout_counter[7] <= _134_;
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) timeout_counter[8] <= 1'h0;
    else if (_008_) timeout_counter[8] <= _135_;
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) timeout_counter[9] <= 1'h0;
    else if (_008_) timeout_counter[9] <= _136_;
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) timeout_counter[10] <= 1'h0;
    else if (_008_) timeout_counter[10] <= _122_;
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) timeout_counter[11] <= 1'h0;
    else if (_008_) timeout_counter[11] <= _123_;
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) timeout_counter[12] <= 1'h0;
    else if (_008_) timeout_counter[12] <= _124_;
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) timeout_counter[13] <= 1'h0;
    else if (_008_) timeout_counter[13] <= _125_;
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) timeout_counter[14] <= 1'h0;
    else if (_008_) timeout_counter[14] <= _126_;
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) timeout_counter[15] <= 1'h0;
    else if (_008_) timeout_counter[15] <= _127_;
  always @(posedge clk_aon_o)
    if (!pd_aon_vdd_i) dvfs_req_prev <= 1'h0;
    else dvfs_req_prev <= dvfs_req_i;
  reg \current_state_reg[0] ;
  always @(posedge clk_aon_o)
    \current_state_reg[0]  <= _002_;
  assign current_state[0] = \current_state_reg[0] ;
  reg \current_state_reg[1] ;
  always @(posedge clk_aon_o)
    \current_state_reg[1]  <= _003_;
  assign current_state[1] = \current_state_reg[1] ;
  reg \current_state_reg[2] ;
  always @(posedge clk_aon_o)
    \current_state_reg[2]  <= _004_;
  assign current_state[2] = \current_state_reg[2] ;
  reg \current_state_reg[3] ;
  always @(posedge clk_aon_o)
    \current_state_reg[3]  <= _001_;
  assign current_state[3] = \current_state_reg[3] ;
  always @(posedge clk_aon_o)
    dvfs_ack_o <= _005_;
  reg \current_state_reg[5] ;
  always @(posedge clk_aon_o)
    \current_state_reg[5]  <= _006_;
  assign current_state[5] = \current_state_reg[5] ;
  reg \clk_status_o_reg[2] ;
  always @(posedge clk_aon_o)
    \clk_status_o_reg[2]  <= _007_;
  assign clk_status_o[2] = \clk_status_o_reg[2] ;
  assign _138_[0] = _137_[0];
  assign _137_[5:1] = aon_div_counter[5:1];
  assign { current_state[6], current_state[4] } = { clk_status_o[2], dvfs_ack_o };
  assign clk_status_o[1] = 1'h0;
  assign clk_io_o = ext_clk_i;
  assign clk_sys_o = ext_clk_i;
endmodule
