/* Generated by Yosys 0.65+37 (git sha1 e87a9bd9a, clang++ 18.1.8 -fPIC -O3) */

module M13_ISADecoder(clk_sys_i, rst_sys_n_i, pg_main_en_i, isa_inst_valid_i, isa_inst_data_i, isa_inst_ready_o, isa_pc_i, isa_pc_update_o, dec_valid_o, dec_opcode_o, dec_format_o, dec_vd_o, dec_vs1_o, dec_vs2_o, dec_vs3_o, dec_sd_o, dec_imm16_o, dec_imm21_o, dec_base_o, dec_offset_o, dec_func_o
, op_valid_o, op_target_o, op_ready_i, op_start_o, op_done_i, sa_cmd_valid_o, sa_op_o, sa_ready_i, mem_addr_o, mem_wen_o, mem_valid_o, mem_ready_i, sec_valid_i, sec_en_i, sched_start_i, sched_pause_i, sched_abort_i, dec_done_o, dec_busy_o, error_invalid_opcode_o, error_invalid_format_o
, error_invalid_reg_o, error_secure_boot_fail_o);
  input clk_sys_i;
  wire clk_sys_i;
  input rst_sys_n_i;
  wire rst_sys_n_i;
  input pg_main_en_i;
  wire pg_main_en_i;
  input isa_inst_valid_i;
  wire isa_inst_valid_i;
  input [31:0] isa_inst_data_i;
  wire [31:0] isa_inst_data_i;
  output isa_inst_ready_o;
  wire isa_inst_ready_o;
  input [31:0] isa_pc_i;
  wire [31:0] isa_pc_i;
  output isa_pc_update_o;
  wire isa_pc_update_o;
  output dec_valid_o;
  reg dec_valid_o;
  output [5:0] dec_opcode_o;
  reg [5:0] dec_opcode_o;
  output [1:0] dec_format_o;
  reg [1:0] dec_format_o;
  output [4:0] dec_vd_o;
  reg [4:0] dec_vd_o;
  output [4:0] dec_vs1_o;
  reg [4:0] dec_vs1_o;
  output [4:0] dec_vs2_o;
  reg [4:0] dec_vs2_o;
  output [4:0] dec_vs3_o;
  reg [4:0] dec_vs3_o;
  output [4:0] dec_sd_o;
  reg [4:0] dec_sd_o;
  output [15:0] dec_imm16_o;
  reg [15:0] dec_imm16_o;
  output [20:0] dec_imm21_o;
  reg [20:0] dec_imm21_o;
  output [4:0] dec_base_o;
  reg [4:0] dec_base_o;
  output [10:0] dec_offset_o;
  reg [10:0] dec_offset_o;
  output [5:0] dec_func_o;
  reg [5:0] dec_func_o;
  output op_valid_o;
  wire op_valid_o;
  output [3:0] op_target_o;
  wire [3:0] op_target_o;
  input op_ready_i;
  wire op_ready_i;
  output op_start_o;
  wire op_start_o;
  input op_done_i;
  wire op_done_i;
  output sa_cmd_valid_o;
  wire sa_cmd_valid_o;
  output [1:0] sa_op_o;
  wire [1:0] sa_op_o;
  input sa_ready_i;
  wire sa_ready_i;
  output [31:0] mem_addr_o;
  wire [31:0] mem_addr_o;
  output mem_wen_o;
  wire mem_wen_o;
  output mem_valid_o;
  wire mem_valid_o;
  input mem_ready_i;
  wire mem_ready_i;
  input sec_valid_i;
  wire sec_valid_i;
  input sec_en_i;
  wire sec_en_i;
  input sched_start_i;
  wire sched_start_i;
  input sched_pause_i;
  wire sched_pause_i;
  input sched_abort_i;
  wire sched_abort_i;
  output dec_done_o;
  wire dec_done_o;
  output dec_busy_o;
  wire dec_busy_o;
  output error_invalid_opcode_o;
  reg error_invalid_opcode_o;
  output error_invalid_format_o;
  reg error_invalid_format_o;
  output error_invalid_reg_o;
  reg error_invalid_reg_o;
  output error_secure_boot_fail_o;
  reg error_secure_boot_fail_o;
  wire [1:0] _000_;
  wire [2:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire [1:0] _299_;
  wire [1:0] _300_;
  reg [1:0] branch_counter;
  wire [2:0] fsm_next_state;
  reg [2:0] fsm_state;
  reg [31:0] inst;
  reg s1_valid;
  reg s2_valid;
  reg s3_valid;
  assign _021_ = ~dec_opcode_o[4];
  assign _299_[0] = ~branch_counter[0];
  assign _022_ = dec_format_o[1] & ~(dec_format_o[0]);
  assign _190_ = inst[6] & _022_;
  assign _189_ = inst[5] & _022_;
  assign _188_ = inst[4] & _022_;
  assign _187_ = inst[3] & _022_;
  assign _186_ = inst[2] & _022_;
  assign _185_ = inst[1] & _022_;
  assign _183_ = inst[0] & _022_;
  assign _023_ = ~(dec_format_o[0] | dec_format_o[1]);
  assign _181_ = inst[4] & _023_;
  assign _180_ = inst[3] & _023_;
  assign _179_ = inst[2] & _023_;
  assign _178_ = inst[1] & _023_;
  assign _177_ = inst[0] & _023_;
  assign _024_ = dec_format_o[0] & ~(dec_format_o[1]);
  assign _224_ = inst[3] & _024_;
  assign _025_ = fsm_state[0] & fsm_state[1];
  assign _026_ = fsm_state[2] & _025_;
  assign _027_ = fsm_state[1] & ~(fsm_state[0]);
  assign _028_ = ~(fsm_state[2] & _027_);
  assign _029_ = ~(fsm_state[1] & fsm_state[2]);
  assign _278_ = isa_inst_data_i[1] & _029_;
  assign _267_ = isa_inst_data_i[0] & _029_;
  assign _030_ = dec_format_o[0] & dec_format_o[1];
  assign _194_ = inst[0] & _030_;
  assign _031_ = ~(fsm_state[0] | fsm_state[1]);
  assign _032_ = fsm_state[2] | ~(_031_);
  assign _008_ = ~_032_;
  assign _033_ = sched_start_i | _032_;
  assign _034_ = sec_en_i | _032_;
  assign _035_ = _033_ & _034_;
  assign _036_ = dec_sd_o[4] & ~(_023_);
  assign _037_ = dec_opcode_o[4] & dec_opcode_o[5];
  assign _038_ = ~(dec_opcode_o[3] | dec_opcode_o[2]);
  assign _039_ = ~(_037_ & _038_);
  assign _040_ = dec_opcode_o[0] | dec_opcode_o[1];
  assign _041_ = dec_opcode_o[3] | _040_;
  assign _042_ = _037_ & ~(_041_);
  assign _043_ = _039_ & ~(_042_);
  assign _044_ = ~(dec_opcode_o[1] & dec_opcode_o[2]);
  assign _045_ = ~(dec_opcode_o[3] | dec_opcode_o[4]);
  assign _046_ = ~(_044_ & _045_);
  assign _047_ = dec_opcode_o[0] & dec_opcode_o[1];
  assign _048_ = dec_opcode_o[2] | dec_opcode_o[4];
  assign _049_ = _047_ | _048_;
  assign _050_ = _046_ & _049_;
  assign _051_ = ~(dec_opcode_o[2] & _041_);
  assign _052_ = dec_opcode_o[4] & ~(dec_opcode_o[5]);
  assign _053_ = ~(_051_ & _052_);
  assign _054_ = _050_ & _053_;
  assign _055_ = _043_ & _054_;
  assign _056_ = ~(_036_ | _055_);
  assign _057_ = ~(dec_sd_o[2] | dec_sd_o[3]);
  assign _058_ = ~(dec_sd_o[0] | dec_sd_o[1]);
  assign _059_ = _058_ & ~(dec_sd_o[4]);
  assign _060_ = ~(_057_ & _059_);
  assign _061_ = ~(_047_ & _060_);
  assign _062_ = _039_ | _061_;
  assign _063_ = _025_ & _062_;
  assign _064_ = ~(_056_ & _063_);
  assign _065_ = fsm_state[2] | ~(fsm_state[1]);
  assign _066_ = fsm_state[0] & ~(fsm_state[2]);
  assign _067_ = ~(fsm_state[2] | _031_);
  assign _068_ = ~(_064_ & _067_);
  assign fsm_next_state[1] = ~(_035_ & _068_);
  assign _069_ = inst[29] | ~(inst[31]);
  assign _070_ = inst[30] & ~(_069_);
  assign _071_ = inst[28] & inst[27];
  assign _072_ = inst[28] & inst[26];
  assign _073_ = inst[26] | ~(inst[28]);
  assign _074_ = ~(_071_ | _072_);
  assign _075_ = ~(_070_ & _074_);
  assign _076_ = ~(inst[28] | inst[26]);
  assign _077_ = ~(inst[27] & _076_);
  assign _078_ = _069_ & _077_;
  assign _079_ = inst[27] ? inst[28] : _073_;
  assign _080_ = inst[30] | _078_;
  assign _081_ = _079_ | _080_;
  assign _000_[0] = ~(_075_ & _081_);
  assign _082_ = fsm_state[0] & ~(fsm_state[1]);
  assign isa_inst_ready_o = _066_ & ~(fsm_state[1]);
  assign op_valid_o = fsm_state[2] & _031_;
  assign _176_ = ~(fsm_state[0] | _065_);
  assign _083_ = ~(_055_ & _176_);
  assign _003_ = ~_083_;
  assign _212_ = inst[7] & _030_;
  assign _220_ = inst[14] & _024_;
  assign _209_ = inst[4] & _030_;
  assign _295_ = isa_inst_data_i[6] & _029_;
  assign _223_ = inst[2] & _024_;
  assign _084_ = dec_opcode_o[3] & ~(dec_opcode_o[2]);
  assign _085_ = ~(dec_opcode_o[4] | dec_opcode_o[5]);
  assign _086_ = dec_opcode_o[0] & ~(dec_opcode_o[1]);
  assign _087_ = _085_ & _086_;
  assign _088_ = dec_opcode_o[0] & ~(dec_opcode_o[2]);
  assign sa_op_o[0] = _084_ & _087_;
  assign _089_ = ~(inst[23] & _030_);
  assign _090_ = ~(inst[13] & _022_);
  assign _238_ = ~(_089_ & _090_);
  assign _091_ = ~(_038_ & _040_);
  assign _092_ = _021_ | _091_;
  assign _093_ = _046_ & _092_;
  assign _094_ = dec_opcode_o[5] | _093_;
  assign _001_[1] = ~(_043_ & _094_);
  assign _095_ = dec_opcode_o[1] & ~(dec_opcode_o[0]);
  assign _096_ = ~(_084_ & _095_);
  assign _097_ = _091_ & _096_;
  assign _098_ = dec_opcode_o[5] | _097_;
  assign _099_ = _050_ & _098_;
  assign _001_[0] = ~(_085_ | _099_);
  assign _265_ = inst[30] & _028_;
  assign _264_ = inst[29] & _028_;
  assign _263_ = inst[28] & _028_;
  assign _210_ = inst[5] & _030_;
  assign _262_ = inst[27] & _028_;
  assign _261_ = inst[26] & _028_;
  assign _175_ = fsm_state[1] & _066_;
  assign _100_ = ~(_062_ & _175_);
  assign _101_ = _056_ | _100_;
  assign _102_ = ~(dec_opcode_o[2] & _042_);
  assign _103_ = fsm_state[2] & _082_;
  assign _104_ = ~(sched_abort_i | sched_pause_i);
  assign _105_ = _103_ & _104_;
  assign _106_ = ~(_102_ & _105_);
  assign _107_ = fsm_state[0] & _106_;
  assign fsm_next_state[0] = ~(_101_ & _107_);
  assign _108_ = ~(inst[22] & _030_);
  assign _109_ = ~(inst[12] & _022_);
  assign _237_ = ~(_108_ & _109_);
  assign _294_ = isa_inst_data_i[5] & _029_;
  assign _290_ = isa_inst_data_i[30] & _029_;
  assign _288_ = isa_inst_data_i[29] & _029_;
  assign _287_ = isa_inst_data_i[28] & _029_;
  assign _219_ = inst[13] & _024_;
  assign _293_ = isa_inst_data_i[4] & _029_;
  assign _292_ = isa_inst_data_i[3] & _029_;
  assign _289_ = isa_inst_data_i[2] & _029_;
  assign _286_ = isa_inst_data_i[27] & _029_;
  assign _296_ = isa_inst_data_i[7] & _029_;
  assign _285_ = isa_inst_data_i[26] & _029_;
  assign _297_ = isa_inst_data_i[8] & _029_;
  assign _283_ = isa_inst_data_i[24] & _029_;
  assign _268_ = isa_inst_data_i[10] & _029_;
  assign _269_ = isa_inst_data_i[11] & _029_;
  assign _282_ = isa_inst_data_i[23] & _029_;
  assign _281_ = isa_inst_data_i[22] & _029_;
  assign _280_ = isa_inst_data_i[21] & _029_;
  assign _270_ = isa_inst_data_i[12] & _029_;
  assign _279_ = isa_inst_data_i[20] & _029_;
  assign _271_ = isa_inst_data_i[13] & _029_;
  assign _277_ = isa_inst_data_i[19] & _029_;
  assign _272_ = isa_inst_data_i[14] & _029_;
  assign _198_ = inst[13] & _030_;
  assign _284_ = isa_inst_data_i[25] & _029_;
  assign _298_ = isa_inst_data_i[9] & _029_;
  assign _276_ = isa_inst_data_i[18] & _029_;
  assign _273_ = isa_inst_data_i[15] & _029_;
  assign _274_ = isa_inst_data_i[16] & _029_;
  assign _275_ = isa_inst_data_i[17] & _029_;
  assign _227_ = inst[6] & _024_;
  assign _207_ = inst[2] & _030_;
  assign _110_ = ~(inst[21] & _030_);
  assign _111_ = ~(inst[11] & _022_);
  assign _236_ = ~(_110_ & _111_);
  assign _259_ = inst[24] & ~(_030_);
  assign _213_ = inst[8] & _030_;
  assign _211_ = inst[6] & _030_;
  assign _228_ = inst[7] & _024_;
  assign _205_ = inst[1] & _030_;
  assign _192_ = inst[8] & _022_;
  assign _258_ = inst[23] & ~(_030_);
  assign _257_ = inst[22] & ~(_030_);
  assign _208_ = inst[3] & _030_;
  assign _196_ = inst[11] & _030_;
  assign _222_ = inst[1] & _024_;
  assign _215_ = inst[0] & _024_;
  assign _256_ = inst[21] & ~(_030_);
  assign _200_ = inst[15] & _030_;
  assign _204_ = inst[19] & _030_;
  assign _254_ = inst[19] & ~(dec_format_o[1]);
  assign _253_ = inst[18] & ~(dec_format_o[1]);
  assign _214_ = inst[9] & _030_;
  assign _252_ = inst[17] & ~(dec_format_o[1]);
  assign _199_ = inst[14] & _030_;
  assign _193_ = inst[9] & _022_;
  assign _112_ = branch_counter[1] | ~(branch_counter[0]);
  assign _113_ = branch_counter[1] & ~(branch_counter[0]);
  assign _300_[1] = branch_counter[1] ^ branch_counter[0];
  assign _251_ = inst[16] & ~(dec_format_o[1]);
  assign _249_ = inst[14] & _023_;
  assign _248_ = inst[13] & _023_;
  assign _114_ = inst[31] & _077_;
  assign _115_ = inst[29] | _071_;
  assign _116_ = ~(inst[28] | inst[27]);
  assign _117_ = ~(inst[26] & _116_);
  assign _118_ = _115_ & _117_;
  assign _119_ = ~(_114_ & _118_);
  assign _120_ = inst[29] & _076_;
  assign _121_ = ~(inst[31] | _120_);
  assign _122_ = ~(inst[30] | _121_);
  assign _123_ = ~(_119_ & _122_);
  assign _000_[1] = ~(_075_ & _123_);
  assign _247_ = inst[12] & _023_;
  assign _246_ = inst[11] & _023_;
  assign _244_ = inst[9] & _023_;
  assign _243_ = inst[8] & _023_;
  assign _242_ = inst[7] & _023_;
  assign _241_ = inst[6] & _023_;
  assign _124_ = _095_ | ~(_084_);
  assign _125_ = ~(_041_ & _124_);
  assign _126_ = ~(_052_ & _125_);
  assign _127_ = dec_opcode_o[5] & ~(_046_);
  assign _128_ = ~(_043_ & _126_);
  assign _001_[2] = _127_ | _128_;
  assign _266_ = inst[31] & _028_;
  assign _235_ = inst[20] & _022_;
  assign _260_ = inst[25] & ~(_030_);
  assign _197_ = inst[12] & _030_;
  assign _129_ = ~(branch_counter[1] | branch_counter[0]);
  assign _130_ = _028_ | _129_;
  assign _131_ = op_target_o[1] & ~(op_target_o[0]);
  assign _132_ = ~(op_target_o[2] & _131_);
  assign _133_ = ~(_103_ & _132_);
  assign _134_ = op_done_i | _133_;
  assign _135_ = _130_ & _134_;
  assign _136_ = ~(pg_main_en_i & s3_valid);
  assign _137_ = op_valid_o | ~(pg_main_en_i);
  assign _138_ = ~(_136_ & _137_);
  assign _139_ = _138_ & ~(_067_);
  assign _011_ = _135_ & _139_;
  assign _140_ = _135_ & ~(_137_);
  assign _141_ = isa_inst_valid_i | ~(isa_inst_ready_o);
  assign _142_ = _065_ & _141_;
  assign _143_ = pg_main_en_i & _141_;
  assign _019_ = _140_ & _142_;
  assign _225_ = inst[4] & _024_;
  assign _144_ = pg_main_en_i & _027_;
  assign _013_ = pg_main_en_i & ~(_028_);
  assign _005_ = sched_start_i & ~(_034_);
  assign _145_ = ~(op_valid_o | _175_);
  assign _146_ = _035_ & _145_;
  assign fsm_next_state[2] = ~(_083_ & _146_);
  assign _234_ = inst[19] & _022_;
  assign _147_ = fsm_state[1] ? fsm_state[2] : _066_;
  assign _148_ = _130_ & _147_;
  assign _016_ = _143_ & _148_;
  assign _221_ = inst[15] & _024_;
  assign _017_ = op_valid_o & ~(_136_);
  assign _245_ = inst[10] & _023_;
  assign _218_ = inst[12] & _024_;
  assign _217_ = inst[11] & _024_;
  assign _226_ = inst[5] & _024_;
  assign _216_ = inst[10] & _024_;
  assign _149_ = s1_valid | ~(_176_);
  assign _150_ = _066_ | ~(_149_);
  assign _015_ = _140_ & ~(_150_);
  assign _203_ = inst[18] & _030_;
  assign _151_ = ~(inst[25] & _030_);
  assign _152_ = ~(inst[15] & _022_);
  assign _240_ = ~(_151_ & _152_);
  assign _255_ = inst[20] & ~(dec_format_o[1]);
  assign _206_ = inst[20] & _030_;
  assign _230_ = inst[9] & _024_;
  assign dec_done_o = _008_ & ~(_102_);
  assign _153_ = _028_ | _113_;
  assign _154_ = rst_sys_n_i & ~(sched_abort_i);
  assign _155_ = ~(_026_ & _154_);
  assign _156_ = _033_ & _155_;
  assign _157_ = _153_ & _156_;
  assign _158_ = ~(op_valid_o & _132_);
  assign _159_ = op_ready_i | _158_;
  assign _160_ = _143_ & _159_;
  assign _161_ = _134_ & _157_;
  assign _018_ = _160_ & _161_;
  assign _162_ = fsm_state[2] ? _025_ : _031_;
  assign dec_busy_o = ~_162_;
  assign _233_ = inst[18] & _022_;
  assign _232_ = inst[17] & _022_;
  assign _163_ = op_target_o[0] & ~(op_target_o[1]);
  assign _164_ = op_target_o[2] & _163_;
  assign mem_valid_o = op_valid_o & _164_;
  assign _165_ = ~(s2_valid & _025_);
  assign _166_ = ~(_067_ & _165_);
  assign _020_ = _140_ & _166_;
  assign _167_ = dec_opcode_o[5] & _088_;
  assign mem_wen_o = _045_ & _167_;
  assign sa_op_o[1] = _085_ & ~(_096_);
  assign _202_ = inst[17] & _030_;
  assign _168_ = ~(inst[24] & _030_);
  assign _169_ = ~(inst[14] & _022_);
  assign _239_ = ~(_168_ & _169_);
  assign _191_ = inst[7] & _022_;
  assign _170_ = ~(op_target_o[1] | op_target_o[0]);
  assign _171_ = _170_ & ~(op_target_o[2]);
  assign sa_cmd_valid_o = op_valid_o & _171_;
  assign _172_ = _130_ & _149_;
  assign _014_ = _144_ & _172_;
  assign op_start_o = op_ready_i & op_valid_o;
  assign _291_ = isa_inst_data_i[31] & _029_;
  assign isa_pc_update_o = ~(_028_ | _112_);
  assign _184_ = inst[10] & _022_;
  assign _201_ = inst[16] & _030_;
  assign _004_ = _036_ & _175_;
  assign _009_ = _008_ | _004_;
  assign _229_ = inst[8] & _024_;
  assign _002_ = _055_ & _175_;
  assign _195_ = inst[10] & _030_;
  assign _250_ = inst[15] & _023_;
  assign _231_ = inst[16] & _022_;
  assign _182_ = inst[5] & _023_;
  assign _173_ = s1_valid & ~(fsm_state[2]);
  assign _012_ = _144_ & _173_;
  assign _006_ = _008_ | _002_;
  assign _174_ = pg_main_en_i & s2_valid;
  assign _010_ = _175_ & _174_;
  assign _007_ = ~(_032_ & _083_);
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_valid_o <= 1'h0;
    else if (_011_) dec_valid_o <= op_valid_o;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_sd_o[0] <= 1'h0;
    else if (_010_) dec_sd_o[0] <= _236_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_sd_o[1] <= 1'h0;
    else if (_010_) dec_sd_o[1] <= _237_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_sd_o[2] <= 1'h0;
    else if (_010_) dec_sd_o[2] <= _238_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_sd_o[3] <= 1'h0;
    else if (_010_) dec_sd_o[3] <= _239_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_sd_o[4] <= 1'h0;
    else if (_010_) dec_sd_o[4] <= _240_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) error_invalid_opcode_o <= 1'h0;
    else if (_007_) error_invalid_opcode_o <= _003_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_base_o[0] <= 1'h0;
    else if (_010_) dec_base_o[0] <= _231_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_base_o[1] <= 1'h0;
    else if (_010_) dec_base_o[1] <= _232_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_base_o[2] <= 1'h0;
    else if (_010_) dec_base_o[2] <= _233_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_base_o[3] <= 1'h0;
    else if (_010_) dec_base_o[3] <= _234_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_base_o[4] <= 1'h0;
    else if (_010_) dec_base_o[4] <= _235_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) error_invalid_format_o <= 1'h0;
    else if (_006_) error_invalid_format_o <= _002_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vd_o[0] <= 1'h0;
    else if (_010_) dec_vd_o[0] <= _256_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vd_o[1] <= 1'h0;
    else if (_010_) dec_vd_o[1] <= _257_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vd_o[2] <= 1'h0;
    else if (_010_) dec_vd_o[2] <= _258_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vd_o[3] <= 1'h0;
    else if (_010_) dec_vd_o[3] <= _259_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vd_o[4] <= 1'h0;
    else if (_010_) dec_vd_o[4] <= _260_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_func_o[0] <= 1'h0;
    else if (_010_) dec_func_o[0] <= _177_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_func_o[1] <= 1'h0;
    else if (_010_) dec_func_o[1] <= _178_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_func_o[2] <= 1'h0;
    else if (_010_) dec_func_o[2] <= _179_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_func_o[3] <= 1'h0;
    else if (_010_) dec_func_o[3] <= _180_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_func_o[4] <= 1'h0;
    else if (_010_) dec_func_o[4] <= _181_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_func_o[5] <= 1'h0;
    else if (_010_) dec_func_o[5] <= _182_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) error_invalid_reg_o <= 1'h0;
    else if (_009_) error_invalid_reg_o <= _004_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) s3_valid <= 1'h0;
    else if (_020_) s3_valid <= _175_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[0] <= 1'h0;
    else if (_010_) dec_imm21_o[0] <= _194_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[1] <= 1'h0;
    else if (_010_) dec_imm21_o[1] <= _205_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[2] <= 1'h0;
    else if (_010_) dec_imm21_o[2] <= _207_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[3] <= 1'h0;
    else if (_010_) dec_imm21_o[3] <= _208_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[4] <= 1'h0;
    else if (_010_) dec_imm21_o[4] <= _209_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[5] <= 1'h0;
    else if (_010_) dec_imm21_o[5] <= _210_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[6] <= 1'h0;
    else if (_010_) dec_imm21_o[6] <= _211_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[7] <= 1'h0;
    else if (_010_) dec_imm21_o[7] <= _212_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[8] <= 1'h0;
    else if (_010_) dec_imm21_o[8] <= _213_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[9] <= 1'h0;
    else if (_010_) dec_imm21_o[9] <= _214_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[10] <= 1'h0;
    else if (_010_) dec_imm21_o[10] <= _195_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[11] <= 1'h0;
    else if (_010_) dec_imm21_o[11] <= _196_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[12] <= 1'h0;
    else if (_010_) dec_imm21_o[12] <= _197_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[13] <= 1'h0;
    else if (_010_) dec_imm21_o[13] <= _198_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[14] <= 1'h0;
    else if (_010_) dec_imm21_o[14] <= _199_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[15] <= 1'h0;
    else if (_010_) dec_imm21_o[15] <= _200_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[16] <= 1'h0;
    else if (_010_) dec_imm21_o[16] <= _201_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[17] <= 1'h0;
    else if (_010_) dec_imm21_o[17] <= _202_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[18] <= 1'h0;
    else if (_010_) dec_imm21_o[18] <= _203_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[19] <= 1'h0;
    else if (_010_) dec_imm21_o[19] <= _204_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm21_o[20] <= 1'h0;
    else if (_010_) dec_imm21_o[20] <= _206_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) error_secure_boot_fail_o <= 1'h0;
    else if (_008_) error_secure_boot_fail_o <= _005_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) s1_valid <= 1'h0;
    else if (_019_) s1_valid <= isa_inst_ready_o;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_offset_o[0] <= 1'h0;
    else if (_010_) dec_offset_o[0] <= _183_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_offset_o[1] <= 1'h0;
    else if (_010_) dec_offset_o[1] <= _185_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_offset_o[2] <= 1'h0;
    else if (_010_) dec_offset_o[2] <= _186_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_offset_o[3] <= 1'h0;
    else if (_010_) dec_offset_o[3] <= _187_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_offset_o[4] <= 1'h0;
    else if (_010_) dec_offset_o[4] <= _188_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_offset_o[5] <= 1'h0;
    else if (_010_) dec_offset_o[5] <= _189_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_offset_o[6] <= 1'h0;
    else if (_010_) dec_offset_o[6] <= _190_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_offset_o[7] <= 1'h0;
    else if (_010_) dec_offset_o[7] <= _191_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_offset_o[8] <= 1'h0;
    else if (_010_) dec_offset_o[8] <= _192_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_offset_o[9] <= 1'h0;
    else if (_010_) dec_offset_o[9] <= _193_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_offset_o[10] <= 1'h0;
    else if (_010_) dec_offset_o[10] <= _184_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) fsm_state[0] <= 1'h0;
    else if (_018_) fsm_state[0] <= fsm_next_state[0];
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) fsm_state[1] <= 1'h0;
    else if (_018_) fsm_state[1] <= fsm_next_state[1];
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) fsm_state[2] <= 1'h0;
    else if (_018_) fsm_state[2] <= fsm_next_state[2];
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vs1_o[0] <= 1'h0;
    else if (_010_) dec_vs1_o[0] <= _251_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vs1_o[1] <= 1'h0;
    else if (_010_) dec_vs1_o[1] <= _252_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vs1_o[2] <= 1'h0;
    else if (_010_) dec_vs1_o[2] <= _253_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vs1_o[3] <= 1'h0;
    else if (_010_) dec_vs1_o[3] <= _254_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vs1_o[4] <= 1'h0;
    else if (_010_) dec_vs1_o[4] <= _255_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[0] <= 1'h0;
    else if (_016_) inst[0] <= _267_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[1] <= 1'h0;
    else if (_016_) inst[1] <= _278_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[2] <= 1'h0;
    else if (_016_) inst[2] <= _289_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[3] <= 1'h0;
    else if (_016_) inst[3] <= _292_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[4] <= 1'h0;
    else if (_016_) inst[4] <= _293_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[5] <= 1'h0;
    else if (_016_) inst[5] <= _294_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[6] <= 1'h0;
    else if (_016_) inst[6] <= _295_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[7] <= 1'h0;
    else if (_016_) inst[7] <= _296_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[8] <= 1'h0;
    else if (_016_) inst[8] <= _297_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[9] <= 1'h0;
    else if (_016_) inst[9] <= _298_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[10] <= 1'h0;
    else if (_016_) inst[10] <= _268_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[11] <= 1'h0;
    else if (_016_) inst[11] <= _269_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[12] <= 1'h0;
    else if (_016_) inst[12] <= _270_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[13] <= 1'h0;
    else if (_016_) inst[13] <= _271_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[14] <= 1'h0;
    else if (_016_) inst[14] <= _272_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[15] <= 1'h0;
    else if (_016_) inst[15] <= _273_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[16] <= 1'h0;
    else if (_016_) inst[16] <= _274_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[17] <= 1'h0;
    else if (_016_) inst[17] <= _275_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[18] <= 1'h0;
    else if (_016_) inst[18] <= _276_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[19] <= 1'h0;
    else if (_016_) inst[19] <= _277_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[20] <= 1'h0;
    else if (_016_) inst[20] <= _279_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[21] <= 1'h0;
    else if (_016_) inst[21] <= _280_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[22] <= 1'h0;
    else if (_016_) inst[22] <= _281_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[23] <= 1'h0;
    else if (_016_) inst[23] <= _282_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[24] <= 1'h0;
    else if (_016_) inst[24] <= _283_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[25] <= 1'h0;
    else if (_016_) inst[25] <= _284_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[26] <= 1'h0;
    else if (_016_) inst[26] <= _285_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[27] <= 1'h0;
    else if (_016_) inst[27] <= _286_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[28] <= 1'h0;
    else if (_016_) inst[28] <= _287_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[29] <= 1'h0;
    else if (_016_) inst[29] <= _288_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[30] <= 1'h0;
    else if (_016_) inst[30] <= _290_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) inst[31] <= 1'h0;
    else if (_016_) inst[31] <= _291_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vs3_o[0] <= 1'h0;
    else if (_010_) dec_vs3_o[0] <= _241_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vs3_o[1] <= 1'h0;
    else if (_010_) dec_vs3_o[1] <= _242_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vs3_o[2] <= 1'h0;
    else if (_010_) dec_vs3_o[2] <= _243_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vs3_o[3] <= 1'h0;
    else if (_010_) dec_vs3_o[3] <= _244_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vs3_o[4] <= 1'h0;
    else if (_010_) dec_vs3_o[4] <= _245_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm16_o[0] <= 1'h0;
    else if (_010_) dec_imm16_o[0] <= _215_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm16_o[1] <= 1'h0;
    else if (_010_) dec_imm16_o[1] <= _222_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm16_o[2] <= 1'h0;
    else if (_010_) dec_imm16_o[2] <= _223_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm16_o[3] <= 1'h0;
    else if (_010_) dec_imm16_o[3] <= _224_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm16_o[4] <= 1'h0;
    else if (_010_) dec_imm16_o[4] <= _225_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm16_o[5] <= 1'h0;
    else if (_010_) dec_imm16_o[5] <= _226_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm16_o[6] <= 1'h0;
    else if (_010_) dec_imm16_o[6] <= _227_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm16_o[7] <= 1'h0;
    else if (_010_) dec_imm16_o[7] <= _228_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm16_o[8] <= 1'h0;
    else if (_010_) dec_imm16_o[8] <= _229_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm16_o[9] <= 1'h0;
    else if (_010_) dec_imm16_o[9] <= _230_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm16_o[10] <= 1'h0;
    else if (_010_) dec_imm16_o[10] <= _216_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm16_o[11] <= 1'h0;
    else if (_010_) dec_imm16_o[11] <= _217_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm16_o[12] <= 1'h0;
    else if (_010_) dec_imm16_o[12] <= _218_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm16_o[13] <= 1'h0;
    else if (_010_) dec_imm16_o[13] <= _219_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm16_o[14] <= 1'h0;
    else if (_010_) dec_imm16_o[14] <= _220_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_imm16_o[15] <= 1'h0;
    else if (_010_) dec_imm16_o[15] <= _221_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) s2_valid <= 1'h0;
    else if (_015_) s2_valid <= _176_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_opcode_o[0] <= 1'h0;
    else if (_014_) dec_opcode_o[0] <= _261_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_opcode_o[1] <= 1'h0;
    else if (_014_) dec_opcode_o[1] <= _262_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_opcode_o[2] <= 1'h0;
    else if (_014_) dec_opcode_o[2] <= _263_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_opcode_o[3] <= 1'h0;
    else if (_014_) dec_opcode_o[3] <= _264_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_opcode_o[4] <= 1'h0;
    else if (_014_) dec_opcode_o[4] <= _265_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_opcode_o[5] <= 1'h0;
    else if (_014_) dec_opcode_o[5] <= _266_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vs2_o[0] <= 1'h0;
    else if (_010_) dec_vs2_o[0] <= _246_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vs2_o[1] <= 1'h0;
    else if (_010_) dec_vs2_o[1] <= _247_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vs2_o[2] <= 1'h0;
    else if (_010_) dec_vs2_o[2] <= _248_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vs2_o[3] <= 1'h0;
    else if (_010_) dec_vs2_o[3] <= _249_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_vs2_o[4] <= 1'h0;
    else if (_010_) dec_vs2_o[4] <= _250_;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) branch_counter[0] <= 1'h0;
    else if (_013_) branch_counter[0] <= _299_[0];
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) branch_counter[1] <= 1'h0;
    else if (_013_) branch_counter[1] <= _300_[1];
  reg \op_target_o_reg[0] ;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) \op_target_o_reg[0]  <= 1'h0;
    else if (_017_) \op_target_o_reg[0]  <= _001_[0];
  assign op_target_o[0] = \op_target_o_reg[0] ;
  reg \op_target_o_reg[1] ;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) \op_target_o_reg[1]  <= 1'h0;
    else if (_017_) \op_target_o_reg[1]  <= _001_[1];
  assign op_target_o[1] = \op_target_o_reg[1] ;
  reg \op_target_o_reg[2] ;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) \op_target_o_reg[2]  <= 1'h0;
    else if (_017_) \op_target_o_reg[2]  <= _001_[2];
  assign op_target_o[2] = \op_target_o_reg[2] ;
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_format_o[0] <= 1'h0;
    else if (_012_) dec_format_o[0] <= _000_[0];
  always @(posedge clk_sys_i, negedge rst_sys_n_i)
    if (!rst_sys_n_i) dec_format_o[1] <= 1'h0;
    else if (_012_) dec_format_o[1] <= _000_[1];
  assign _300_[0] = _299_[0];
  assign _299_[1] = branch_counter[1];
  assign mem_addr_o = { 16'h0000, dec_base_o, dec_offset_o };
  assign op_target_o[3] = 1'h0;
endmodule
