/* Generated by Yosys 0.65+37 (git sha1 e87a9bd9a, clang++ 18.1.8 -fPIC -O3) */

module M15_JTAGInterface(tck, tms, tdi, tdo, trst_n, tdo_en, test_mode_en, test_mode_valid, sec_boot_en, test_access_grant, test_access_denied, scan_select, scan_enable, scan_in, scan_out, scan_capture, scan_update, bsr_select, bsr_capture, bsr_update, bsr_data_in
, bsr_data_out, debug_addr, debug_data_in, debug_data_out, debug_rw, debug_valid, debug_ack, mbist_start, mbist_stop, mbist_target, mbist_algorithm, mbist_status, rst_io_n);
  input tck;
  wire tck;
  input tms;
  wire tms;
  input tdi;
  wire tdi;
  output tdo;
  wire tdo;
  input trst_n;
  wire trst_n;
  output tdo_en;
  wire tdo_en;
  input test_mode_en;
  wire test_mode_en;
  input test_mode_valid;
  wire test_mode_valid;
  input sec_boot_en;
  wire sec_boot_en;
  output test_access_grant;
  wire test_access_grant;
  output test_access_denied;
  wire test_access_denied;
  output [3:0] scan_select;
  wire [3:0] scan_select;
  output scan_enable;
  reg scan_enable;
  output scan_in;
  wire scan_in;
  input scan_out;
  wire scan_out;
  output scan_capture;
  reg scan_capture;
  output scan_update;
  reg scan_update;
  output bsr_select;
  wire bsr_select;
  output bsr_capture;
  wire bsr_capture;
  output bsr_update;
  wire bsr_update;
  input [23:0] bsr_data_in;
  wire [23:0] bsr_data_in;
  output [23:0] bsr_data_out;
  reg [23:0] bsr_data_out;
  output [15:0] debug_addr;
  wire [15:0] debug_addr;
  output [31:0] debug_data_in;
  wire [31:0] debug_data_in;
  input [31:0] debug_data_out;
  wire [31:0] debug_data_out;
  output debug_rw;
  wire debug_rw;
  output debug_valid;
  wire debug_valid;
  input debug_ack;
  wire debug_ack;
  output mbist_start;
  wire mbist_start;
  output mbist_stop;
  wire mbist_stop;
  output [1:0] mbist_target;
  wire [1:0] mbist_target;
  output [3:0] mbist_algorithm;
  wire [3:0] mbist_algorithm;
  input [23:0] mbist_status;
  wire [23:0] mbist_status;
  input rst_io_n;
  wire rst_io_n;
  wire [23:0] _000_;
  wire _001_;
  wire [31:0] _002_;
  wire [4:0] _003_;
  wire [4:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  reg [23:0] dr_bsr_reg;
  reg dr_bypass_reg;
  reg [31:0] dr_idcode_reg;
  reg [4:0] ir_shift_reg;
  reg [4:0] ir_update_reg;
  wire [15:0] tap_state;
  assign _027_ = ~(ir_update_reg[0] | ir_update_reg[4]);
  assign _028_ = ~(ir_update_reg[2] | ir_update_reg[3]);
  assign _029_ = ir_update_reg[1] & _028_;
  assign bsr_select = _027_ & _029_;
  assign bsr_capture = scan_capture & bsr_select;
  assign _030_ = bsr_capture ? bsr_data_in[22] : dr_bsr_reg[23];
  assign _000_[22] = rst_io_n & _030_;
  assign _031_ = bsr_capture ? bsr_data_in[21] : dr_bsr_reg[22];
  assign _000_[21] = rst_io_n & _031_;
  assign _032_ = bsr_capture ? bsr_data_in[20] : dr_bsr_reg[21];
  assign _000_[20] = rst_io_n & _032_;
  assign _033_ = bsr_capture ? bsr_data_in[19] : dr_bsr_reg[20];
  assign _000_[19] = rst_io_n & _033_;
  assign _034_ = bsr_capture ? bsr_data_in[18] : dr_bsr_reg[19];
  assign _000_[18] = rst_io_n & _034_;
  assign _035_ = bsr_capture ? bsr_data_in[17] : dr_bsr_reg[18];
  assign _000_[17] = rst_io_n & _035_;
  assign _036_ = bsr_capture ? bsr_data_in[16] : dr_bsr_reg[17];
  assign _000_[16] = rst_io_n & _036_;
  assign _037_ = bsr_capture ? bsr_data_in[15] : dr_bsr_reg[16];
  assign _000_[15] = rst_io_n & _037_;
  assign _038_ = bsr_capture ? bsr_data_in[14] : dr_bsr_reg[15];
  assign _000_[14] = rst_io_n & _038_;
  assign _039_ = bsr_capture ? bsr_data_in[13] : dr_bsr_reg[14];
  assign _000_[13] = rst_io_n & _039_;
  assign _040_ = bsr_capture ? bsr_data_in[12] : dr_bsr_reg[13];
  assign _000_[12] = rst_io_n & _040_;
  assign _041_ = bsr_capture ? bsr_data_in[11] : dr_bsr_reg[12];
  assign _000_[11] = rst_io_n & _041_;
  assign _042_ = bsr_capture ? bsr_data_in[10] : dr_bsr_reg[11];
  assign _000_[10] = rst_io_n & _042_;
  assign _043_ = bsr_capture ? bsr_data_in[9] : dr_bsr_reg[10];
  assign _000_[9] = rst_io_n & _043_;
  assign _044_ = bsr_capture ? bsr_data_in[8] : dr_bsr_reg[9];
  assign _000_[8] = rst_io_n & _044_;
  assign _045_ = bsr_capture ? bsr_data_in[7] : dr_bsr_reg[8];
  assign _000_[7] = rst_io_n & _045_;
  assign _046_ = bsr_capture ? bsr_data_in[6] : dr_bsr_reg[7];
  assign _000_[6] = rst_io_n & _046_;
  assign _047_ = bsr_capture ? bsr_data_in[5] : dr_bsr_reg[6];
  assign _000_[5] = rst_io_n & _047_;
  assign _048_ = bsr_capture ? bsr_data_in[4] : dr_bsr_reg[5];
  assign _000_[4] = rst_io_n & _048_;
  assign _049_ = bsr_capture ? bsr_data_in[3] : dr_bsr_reg[4];
  assign _000_[3] = rst_io_n & _049_;
  assign _050_ = bsr_capture ? bsr_data_in[2] : dr_bsr_reg[3];
  assign _000_[2] = rst_io_n & _050_;
  assign _051_ = bsr_capture ? bsr_data_in[1] : dr_bsr_reg[2];
  assign _000_[1] = rst_io_n & _051_;
  assign _052_ = bsr_capture ? bsr_data_in[0] : dr_bsr_reg[1];
  assign _000_[0] = rst_io_n & _052_;
  assign _053_ = _028_ & ~(ir_update_reg[1]);
  assign _054_ = ir_update_reg[0] & ~(ir_update_reg[4]);
  assign _055_ = _053_ & _054_;
  assign _056_ = ~(scan_capture & _055_);
  assign _057_ = rst_io_n & _056_;
  assign _002_[9] = dr_idcode_reg[10] | ~(_057_);
  assign _058_ = rst_io_n & tap_state[5];
  assign _059_ = ~(ir_update_reg[2] & _058_);
  assign _060_ = rst_io_n & ~(tap_state[5]);
  assign _061_ = ~(ir_shift_reg[4] & _060_);
  assign _003_[3] = ~(_059_ & _061_);
  assign _062_ = ~(ir_update_reg[1] & _058_);
  assign _063_ = ~(ir_shift_reg[3] & _060_);
  assign _003_[2] = ~(_062_ & _063_);
  assign _064_ = ~(ir_update_reg[0] & _058_);
  assign _065_ = ~(ir_shift_reg[2] & _060_);
  assign _003_[1] = ~(_064_ & _065_);
  assign _003_[0] = ir_shift_reg[1] | ~(_060_);
  assign _002_[8] = dr_idcode_reg[9] & _057_;
  assign _004_[3] = rst_io_n & ir_shift_reg[3];
  assign _004_[2] = rst_io_n & ir_shift_reg[2];
  assign _004_[1] = rst_io_n & ir_shift_reg[1];
  assign _004_[0] = ir_shift_reg[0] | ~(rst_io_n);
  assign _002_[29] = dr_idcode_reg[30] & _057_;
  assign _002_[7] = dr_idcode_reg[8] | ~(_057_);
  assign _002_[6] = dr_idcode_reg[7] & _057_;
  assign _002_[5] = dr_idcode_reg[6] | ~(_057_);
  assign _002_[28] = dr_idcode_reg[29] | ~(_057_);
  assign _002_[27] = dr_idcode_reg[28] & _057_;
  assign _002_[4] = dr_idcode_reg[5] | ~(_057_);
  assign _002_[3] = dr_idcode_reg[4] | ~(_057_);
  assign _002_[26] = dr_idcode_reg[27] & _057_;
  assign _002_[25] = dr_idcode_reg[26] | ~(_057_);
  assign _002_[24] = dr_idcode_reg[25] & _057_;
  assign _002_[2] = dr_idcode_reg[3] & _057_;
  assign _002_[1] = dr_idcode_reg[2] & _057_;
  assign _002_[0] = dr_idcode_reg[1] | ~(_057_);
  assign _002_[23] = dr_idcode_reg[24] & _057_;
  assign _002_[22] = dr_idcode_reg[23] & _057_;
  assign _002_[21] = dr_idcode_reg[22] | ~(_057_);
  assign _002_[20] = dr_idcode_reg[21] | ~(_057_);
  assign _002_[19] = dr_idcode_reg[20] & _057_;
  assign _002_[30] = dr_idcode_reg[31] & _057_;
  assign _002_[18] = dr_idcode_reg[19] | ~(_057_);
  assign _066_ = scan_enable | scan_capture;
  assign _067_ = ~(bsr_select & _066_);
  assign _021_ = ~(rst_io_n & _067_);
  assign _002_[17] = dr_idcode_reg[18] & _057_;
  assign _002_[16] = dr_idcode_reg[17] & _057_;
  assign _068_ = _027_ & _053_;
  assign _069_ = ~(_066_ & _068_);
  assign _022_ = ~(rst_io_n & _069_);
  assign _002_[15] = dr_idcode_reg[16] & _057_;
  assign _002_[14] = dr_idcode_reg[15] | ~(_057_);
  assign _070_ = ~(_055_ & _066_);
  assign _023_ = ~(rst_io_n & _070_);
  assign _002_[13] = dr_idcode_reg[14] & _057_;
  assign _002_[12] = dr_idcode_reg[13] | ~(_057_);
  assign bsr_update = scan_update & bsr_select;
  assign _071_ = ~(tap_state[5] | tap_state[13]);
  assign _024_ = tap_state[13] | ~(_060_);
  assign _002_[11] = dr_idcode_reg[12] | ~(_057_);
  assign _002_[10] = dr_idcode_reg[11] & _057_;
  assign _072_ = rst_io_n & tms;
  assign _011_ = tap_state[4] & _072_;
  assign _073_ = ~(tap_state[0] | tap_state[15]);
  assign _074_ = ~(scan_update | tap_state[8]);
  assign _075_ = ~(_073_ & _074_);
  assign _076_ = _073_ & ~(_071_);
  assign _077_ = rst_io_n & ~(tms);
  assign _078_ = _075_ & _077_;
  assign _020_ = _078_ & ~(_076_);
  assign _079_ = tap_state[7] | _076_;
  assign _018_ = _077_ & _079_;
  assign _010_ = tap_state[11] & _072_;
  assign _080_ = tap_state[6] | tap_state[10];
  assign _009_ = _077_ & _080_;
  assign _008_ = tap_state[9] & _077_;
  assign _081_ = _071_ & _072_;
  assign _082_ = _073_ & ~(_074_);
  assign _007_ = _081_ & _082_;
  assign _006_ = _072_ & _076_;
  assign _083_ = ~(_066_ & _071_);
  assign _084_ = ~(_075_ | _083_);
  assign _085_ = tap_state[14] | _084_;
  assign _019_ = _077_ & _085_;
  assign _014_ = tap_state[4] & _077_;
  assign _086_ = tap_state[10] | tap_state[14];
  assign _005_ = _072_ & _086_;
  assign _087_ = tap_state[3] | tap_state[11];
  assign _013_ = _077_ & _087_;
  assign _088_ = rst_io_n & ~(tap_state[9]);
  assign _089_ = _073_ & _088_;
  assign _017_ = ~(_077_ | _089_);
  assign tdo_en = tap_state[13] | scan_enable;
  assign _004_[4] = rst_io_n & ir_shift_reg[4];
  assign _090_ = bsr_select ? dr_bsr_reg[0] : dr_bypass_reg;
  assign _091_ = _055_ | ~(_090_);
  assign _092_ = ~(dr_idcode_reg[0] & _055_);
  assign _093_ = scan_enable & _092_;
  assign _094_ = ~(_091_ & _093_);
  assign _095_ = ir_shift_reg[0] & tap_state[13];
  assign _096_ = scan_enable | _095_;
  assign tdo = _094_ & _096_;
  assign _097_ = ~(scan_capture & _068_);
  assign _098_ = rst_io_n & tdi;
  assign _001_ = _097_ & _098_;
  assign _099_ = ~(tdi & _060_);
  assign _100_ = ~(ir_update_reg[3] & _058_);
  assign _003_[4] = ~(_099_ & _100_);
  assign _101_ = ~(tap_state[15] & _071_);
  assign _025_ = ~(rst_io_n & _101_);
  assign _002_[31] = tdi & _057_;
  assign _102_ = ~(trst_n & bsr_update);
  assign _026_ = ~(_021_ | _102_);
  assign _103_ = bsr_capture ? bsr_data_in[23] : tdi;
  assign _000_[23] = rst_io_n & _103_;
  assign _104_ = test_mode_en & test_mode_valid;
  assign test_access_grant = sec_boot_en & _104_;
  assign test_access_denied = test_mode_en & ~(test_mode_valid);
  assign _105_ = tap_state[3] | tap_state[7];
  assign _016_ = _072_ & _105_;
  assign _015_ = tap_state[6] & _072_;
  assign _012_ = _072_ & _084_;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) ir_shift_reg[0] <= 1'h1;
    else if (_024_) ir_shift_reg[0] <= _003_[0];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) ir_shift_reg[1] <= 1'h0;
    else if (_024_) ir_shift_reg[1] <= _003_[1];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) ir_shift_reg[2] <= 1'h0;
    else if (_024_) ir_shift_reg[2] <= _003_[2];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) ir_shift_reg[3] <= 1'h0;
    else if (_024_) ir_shift_reg[3] <= _003_[3];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) ir_shift_reg[4] <= 1'h0;
    else if (_024_) ir_shift_reg[4] <= _003_[4];
  always @(posedge tck)
    if (_026_) bsr_data_out[0] <= dr_bsr_reg[0];
  always @(posedge tck)
    if (_026_) bsr_data_out[1] <= dr_bsr_reg[1];
  always @(posedge tck)
    if (_026_) bsr_data_out[2] <= dr_bsr_reg[2];
  always @(posedge tck)
    if (_026_) bsr_data_out[3] <= dr_bsr_reg[3];
  always @(posedge tck)
    if (_026_) bsr_data_out[4] <= dr_bsr_reg[4];
  always @(posedge tck)
    if (_026_) bsr_data_out[5] <= dr_bsr_reg[5];
  always @(posedge tck)
    if (_026_) bsr_data_out[6] <= dr_bsr_reg[6];
  always @(posedge tck)
    if (_026_) bsr_data_out[7] <= dr_bsr_reg[7];
  always @(posedge tck)
    if (_026_) bsr_data_out[8] <= dr_bsr_reg[8];
  always @(posedge tck)
    if (_026_) bsr_data_out[9] <= dr_bsr_reg[9];
  always @(posedge tck)
    if (_026_) bsr_data_out[10] <= dr_bsr_reg[10];
  always @(posedge tck)
    if (_026_) bsr_data_out[11] <= dr_bsr_reg[11];
  always @(posedge tck)
    if (_026_) bsr_data_out[12] <= dr_bsr_reg[12];
  always @(posedge tck)
    if (_026_) bsr_data_out[13] <= dr_bsr_reg[13];
  always @(posedge tck)
    if (_026_) bsr_data_out[14] <= dr_bsr_reg[14];
  always @(posedge tck)
    if (_026_) bsr_data_out[15] <= dr_bsr_reg[15];
  always @(posedge tck)
    if (_026_) bsr_data_out[16] <= dr_bsr_reg[16];
  always @(posedge tck)
    if (_026_) bsr_data_out[17] <= dr_bsr_reg[17];
  always @(posedge tck)
    if (_026_) bsr_data_out[18] <= dr_bsr_reg[18];
  always @(posedge tck)
    if (_026_) bsr_data_out[19] <= dr_bsr_reg[19];
  always @(posedge tck)
    if (_026_) bsr_data_out[20] <= dr_bsr_reg[20];
  always @(posedge tck)
    if (_026_) bsr_data_out[21] <= dr_bsr_reg[21];
  always @(posedge tck)
    if (_026_) bsr_data_out[22] <= dr_bsr_reg[22];
  always @(posedge tck)
    if (_026_) bsr_data_out[23] <= dr_bsr_reg[23];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[0] <= 1'h1;
    else if (_023_) dr_idcode_reg[0] <= _002_[0];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[1] <= 1'h0;
    else if (_023_) dr_idcode_reg[1] <= _002_[1];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[2] <= 1'h0;
    else if (_023_) dr_idcode_reg[2] <= _002_[2];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[3] <= 1'h1;
    else if (_023_) dr_idcode_reg[3] <= _002_[3];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[4] <= 1'h1;
    else if (_023_) dr_idcode_reg[4] <= _002_[4];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[5] <= 1'h1;
    else if (_023_) dr_idcode_reg[5] <= _002_[5];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[6] <= 1'h0;
    else if (_023_) dr_idcode_reg[6] <= _002_[6];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[7] <= 1'h1;
    else if (_023_) dr_idcode_reg[7] <= _002_[7];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[8] <= 1'h0;
    else if (_023_) dr_idcode_reg[8] <= _002_[8];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[9] <= 1'h1;
    else if (_023_) dr_idcode_reg[9] <= _002_[9];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[10] <= 1'h0;
    else if (_023_) dr_idcode_reg[10] <= _002_[10];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[11] <= 1'h1;
    else if (_023_) dr_idcode_reg[11] <= _002_[11];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[12] <= 1'h1;
    else if (_023_) dr_idcode_reg[12] <= _002_[12];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[13] <= 1'h0;
    else if (_023_) dr_idcode_reg[13] <= _002_[13];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[14] <= 1'h1;
    else if (_023_) dr_idcode_reg[14] <= _002_[14];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[15] <= 1'h0;
    else if (_023_) dr_idcode_reg[15] <= _002_[15];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[16] <= 1'h0;
    else if (_023_) dr_idcode_reg[16] <= _002_[16];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[17] <= 1'h0;
    else if (_023_) dr_idcode_reg[17] <= _002_[17];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[18] <= 1'h1;
    else if (_023_) dr_idcode_reg[18] <= _002_[18];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[19] <= 1'h0;
    else if (_023_) dr_idcode_reg[19] <= _002_[19];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[20] <= 1'h1;
    else if (_023_) dr_idcode_reg[20] <= _002_[20];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[21] <= 1'h1;
    else if (_023_) dr_idcode_reg[21] <= _002_[21];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[22] <= 1'h0;
    else if (_023_) dr_idcode_reg[22] <= _002_[22];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[23] <= 1'h0;
    else if (_023_) dr_idcode_reg[23] <= _002_[23];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[24] <= 1'h0;
    else if (_023_) dr_idcode_reg[24] <= _002_[24];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[25] <= 1'h1;
    else if (_023_) dr_idcode_reg[25] <= _002_[25];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[26] <= 1'h0;
    else if (_023_) dr_idcode_reg[26] <= _002_[26];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[27] <= 1'h0;
    else if (_023_) dr_idcode_reg[27] <= _002_[27];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[28] <= 1'h1;
    else if (_023_) dr_idcode_reg[28] <= _002_[28];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[29] <= 1'h0;
    else if (_023_) dr_idcode_reg[29] <= _002_[29];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[30] <= 1'h0;
    else if (_023_) dr_idcode_reg[30] <= _002_[30];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_idcode_reg[31] <= 1'h0;
    else if (_023_) dr_idcode_reg[31] <= _002_[31];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bypass_reg <= 1'h0;
    else if (_022_) dr_bypass_reg <= _001_;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[0] <= 1'h0;
    else if (_021_) dr_bsr_reg[0] <= _000_[0];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[1] <= 1'h0;
    else if (_021_) dr_bsr_reg[1] <= _000_[1];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[2] <= 1'h0;
    else if (_021_) dr_bsr_reg[2] <= _000_[2];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[3] <= 1'h0;
    else if (_021_) dr_bsr_reg[3] <= _000_[3];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[4] <= 1'h0;
    else if (_021_) dr_bsr_reg[4] <= _000_[4];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[5] <= 1'h0;
    else if (_021_) dr_bsr_reg[5] <= _000_[5];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[6] <= 1'h0;
    else if (_021_) dr_bsr_reg[6] <= _000_[6];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[7] <= 1'h0;
    else if (_021_) dr_bsr_reg[7] <= _000_[7];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[8] <= 1'h0;
    else if (_021_) dr_bsr_reg[8] <= _000_[8];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[9] <= 1'h0;
    else if (_021_) dr_bsr_reg[9] <= _000_[9];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[10] <= 1'h0;
    else if (_021_) dr_bsr_reg[10] <= _000_[10];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[11] <= 1'h0;
    else if (_021_) dr_bsr_reg[11] <= _000_[11];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[12] <= 1'h0;
    else if (_021_) dr_bsr_reg[12] <= _000_[12];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[13] <= 1'h0;
    else if (_021_) dr_bsr_reg[13] <= _000_[13];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[14] <= 1'h0;
    else if (_021_) dr_bsr_reg[14] <= _000_[14];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[15] <= 1'h0;
    else if (_021_) dr_bsr_reg[15] <= _000_[15];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[16] <= 1'h0;
    else if (_021_) dr_bsr_reg[16] <= _000_[16];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[17] <= 1'h0;
    else if (_021_) dr_bsr_reg[17] <= _000_[17];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[18] <= 1'h0;
    else if (_021_) dr_bsr_reg[18] <= _000_[18];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[19] <= 1'h0;
    else if (_021_) dr_bsr_reg[19] <= _000_[19];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[20] <= 1'h0;
    else if (_021_) dr_bsr_reg[20] <= _000_[20];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[21] <= 1'h0;
    else if (_021_) dr_bsr_reg[21] <= _000_[21];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[22] <= 1'h0;
    else if (_021_) dr_bsr_reg[22] <= _000_[22];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) dr_bsr_reg[23] <= 1'h0;
    else if (_021_) dr_bsr_reg[23] <= _000_[23];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) ir_update_reg[0] <= 1'h1;
    else if (_025_) ir_update_reg[0] <= _004_[0];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) ir_update_reg[1] <= 1'h0;
    else if (_025_) ir_update_reg[1] <= _004_[1];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) ir_update_reg[2] <= 1'h0;
    else if (_025_) ir_update_reg[2] <= _004_[2];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) ir_update_reg[3] <= 1'h0;
    else if (_025_) ir_update_reg[3] <= _004_[3];
  always @(posedge tck, negedge trst_n)
    if (!trst_n) ir_update_reg[4] <= 1'h0;
    else if (_025_) ir_update_reg[4] <= _004_[4];
  reg \tap_state_reg[0] ;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) \tap_state_reg[0]  <= 1'h1;
    else \tap_state_reg[0]  <= _017_;
  assign tap_state[0] = \tap_state_reg[0] ;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) scan_update <= 1'h0;
    else scan_update <= _005_;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) scan_enable <= 1'h0;
    else scan_enable <= _019_;
  reg \tap_state_reg[3] ;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) \tap_state_reg[3]  <= 1'h0;
    else \tap_state_reg[3]  <= _006_;
  assign tap_state[3] = \tap_state_reg[3] ;
  reg \tap_state_reg[4] ;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) \tap_state_reg[4]  <= 1'h0;
    else \tap_state_reg[4]  <= _007_;
  assign tap_state[4] = \tap_state_reg[4] ;
  reg \tap_state_reg[5] ;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) \tap_state_reg[5]  <= 1'h0;
    else \tap_state_reg[5]  <= _008_;
  assign tap_state[5] = \tap_state_reg[5] ;
  reg \tap_state_reg[6] ;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) \tap_state_reg[6]  <= 1'h0;
    else \tap_state_reg[6]  <= _009_;
  assign tap_state[6] = \tap_state_reg[6] ;
  reg \tap_state_reg[7] ;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) \tap_state_reg[7]  <= 1'h0;
    else \tap_state_reg[7]  <= _010_;
  assign tap_state[7] = \tap_state_reg[7] ;
  reg \tap_state_reg[8] ;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) \tap_state_reg[8]  <= 1'h0;
    else \tap_state_reg[8]  <= _020_;
  assign tap_state[8] = \tap_state_reg[8] ;
  reg \tap_state_reg[9] ;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) \tap_state_reg[9]  <= 1'h0;
    else \tap_state_reg[9]  <= _011_;
  assign tap_state[9] = \tap_state_reg[9] ;
  reg \tap_state_reg[10] ;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) \tap_state_reg[10]  <= 1'h0;
    else \tap_state_reg[10]  <= _012_;
  assign tap_state[10] = \tap_state_reg[10] ;
  reg \tap_state_reg[11] ;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) \tap_state_reg[11]  <= 1'h0;
    else \tap_state_reg[11]  <= _013_;
  assign tap_state[11] = \tap_state_reg[11] ;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) scan_capture <= 1'h0;
    else scan_capture <= _014_;
  reg \tap_state_reg[13] ;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) \tap_state_reg[13]  <= 1'h0;
    else \tap_state_reg[13]  <= _018_;
  assign tap_state[13] = \tap_state_reg[13] ;
  reg \tap_state_reg[14] ;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) \tap_state_reg[14]  <= 1'h0;
    else \tap_state_reg[14]  <= _015_;
  assign tap_state[14] = \tap_state_reg[14] ;
  reg \tap_state_reg[15] ;
  always @(posedge tck, negedge trst_n)
    if (!trst_n) \tap_state_reg[15]  <= 1'h0;
    else \tap_state_reg[15]  <= _016_;
  assign tap_state[15] = \tap_state_reg[15] ;
  assign { tap_state[12], tap_state[2:1] } = { scan_capture, scan_enable, scan_update };
  assign mbist_algorithm = 4'h0;
  assign mbist_target = 2'h0;
  assign mbist_stop = 1'h0;
  assign mbist_start = 1'h0;
  assign debug_valid = 1'h0;
  assign debug_rw = 1'h0;
  assign debug_data_in = 32'd0;
  assign debug_addr = 16'h0000;
  assign scan_in = tdi;
  assign scan_select = 4'h1;
endmodule
