/* Generated by Yosys 0.65+37 (git sha1 e87a9bd9a, clang++ 18.1.8 -fPIC -O3) */

module M16_ISAInterface(ISA_IF, ISA_CLK, ISA_VALID, ISA_DIR, ISA_READY, isa_data_sys_o, isa_valid_sys_o, isa_ready_sys_i, isa_req_sys_o, isa_pc_o, m16_reset_n_i, m16_enable_i, m16_mode_i, sec_boot_done_i, sec_status_pass_i, sec_status_fail_i, sec_lockdown_i, isa_access_grant_o, isa_access_denied_o, isa_crc_error_o, isa_auth_token_i
, clk_sys_i, rst_sys_n_i, error_cdc_timeout_o, error_invalid_opcode_o, error_security_o, error_crc_o);
  inout [15:0] ISA_IF;
  wire [15:0] ISA_IF;
  input ISA_CLK;
  wire ISA_CLK;
  output ISA_VALID;
  wire ISA_VALID;
  output ISA_DIR;
  wire ISA_DIR;
  input ISA_READY;
  wire ISA_READY;
  output [31:0] isa_data_sys_o;
  wire [31:0] isa_data_sys_o;
  output isa_valid_sys_o;
  wire isa_valid_sys_o;
  input isa_ready_sys_i;
  wire isa_ready_sys_i;
  output isa_req_sys_o;
  wire isa_req_sys_o;
  output [31:0] isa_pc_o;
  wire [31:0] isa_pc_o;
  input m16_reset_n_i;
  wire m16_reset_n_i;
  input m16_enable_i;
  wire m16_enable_i;
  input [1:0] m16_mode_i;
  wire [1:0] m16_mode_i;
  input sec_boot_done_i;
  wire sec_boot_done_i;
  input sec_status_pass_i;
  wire sec_status_pass_i;
  input sec_status_fail_i;
  wire sec_status_fail_i;
  input sec_lockdown_i;
  wire sec_lockdown_i;
  output isa_access_grant_o;
  wire isa_access_grant_o;
  output isa_access_denied_o;
  wire isa_access_denied_o;
  output isa_crc_error_o;
  wire isa_crc_error_o;
  input [127:0] isa_auth_token_i;
  wire [127:0] isa_auth_token_i;
  input clk_sys_i;
  wire clk_sys_i;
  input rst_sys_n_i;
  wire rst_sys_n_i;
  output error_cdc_timeout_o;
  wire error_cdc_timeout_o;
  output error_invalid_opcode_o;
  wire error_invalid_opcode_o;
  output error_security_o;
  wire error_security_o;
  output error_crc_o;
  reg error_crc_o;
  wire [7:0] _000_;
  wire [7:0] _001_;
  wire _002_;
  wire [1:0] _003_;
  wire [7:0] _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  reg [7:0] boot_timeout_cnt;
  reg [7:0] cdc_timeout_cnt;
  reg cdc_timeout_flag;
  reg [1:0] fetch_count;
  wire [2:0] fsm1_next_state;
  reg [2:0] fsm1_state;
  wire [10:0] fsm2_state;
  reg [6:0] fsm3_state;
  reg [7:0] parse_timeout_cnt;
  reg rst_sys_n_sync1;
  reg rst_sys_n_sync2;
  assign _022_ = ~cdc_timeout_cnt[0];
  assign _023_ = ~boot_timeout_cnt[0];
  assign _024_ = ~(fsm1_state[1] | fsm1_state[0]);
  assign _025_ = ~_024_;
  assign ISA_VALID = fsm1_state[2] & _024_;
  assign _026_ = fsm1_state[2] | _024_;
  assign _027_ = fsm1_state[1] | ~(fsm1_state[0]);
  assign _002_ = fsm1_state[2] ? _027_ : _025_;
  assign _028_ = cdc_timeout_cnt[1] & cdc_timeout_cnt[0];
  assign _029_ = cdc_timeout_cnt[2] & _028_;
  assign _030_ = cdc_timeout_cnt[3] & _029_;
  assign _031_ = cdc_timeout_cnt[4] & _030_;
  assign _032_ = cdc_timeout_cnt[5] & _031_;
  assign _033_ = cdc_timeout_cnt[6] & _032_;
  assign _034_ = cdc_timeout_cnt[6] | _032_;
  assign _035_ = _002_ & _034_;
  assign _001_[6] = _035_ & ~(_033_);
  assign _036_ = cdc_timeout_cnt[5] | _031_;
  assign _037_ = _002_ & _036_;
  assign _001_[5] = _037_ & ~(_032_);
  assign _038_ = cdc_timeout_cnt[4] | _030_;
  assign _039_ = _002_ & _038_;
  assign _001_[4] = _039_ & ~(_031_);
  assign _040_ = cdc_timeout_cnt[3] | _029_;
  assign _041_ = _002_ & _040_;
  assign _001_[3] = _041_ & ~(_030_);
  assign _042_ = cdc_timeout_cnt[2] ^ _028_;
  assign _001_[2] = _002_ & _042_;
  assign _043_ = cdc_timeout_cnt[1] ^ cdc_timeout_cnt[0];
  assign _001_[1] = _002_ & _043_;
  assign _001_[0] = _022_ & _002_;
  assign _003_[0] = ~(fsm2_state[0] | fetch_count[0]);
  assign _044_ = parse_timeout_cnt[0] & parse_timeout_cnt[1];
  assign _045_ = parse_timeout_cnt[2] & _044_;
  assign _046_ = parse_timeout_cnt[3] & _045_;
  assign _047_ = parse_timeout_cnt[4] & _046_;
  assign _048_ = parse_timeout_cnt[5] & _047_;
  assign _049_ = parse_timeout_cnt[6] & _048_;
  assign _050_ = parse_timeout_cnt[6] | _048_;
  assign _051_ = ~(fsm2_state[0] | ISA_VALID);
  assign _052_ = _050_ & _051_;
  assign _004_[6] = _052_ & ~(_049_);
  assign _053_ = parse_timeout_cnt[5] | _047_;
  assign _054_ = _051_ & _053_;
  assign _004_[5] = _054_ & ~(_048_);
  assign _055_ = parse_timeout_cnt[4] | _046_;
  assign _056_ = _051_ & _055_;
  assign _004_[4] = _056_ & ~(_047_);
  assign _057_ = parse_timeout_cnt[3] | _045_;
  assign _058_ = _051_ & _057_;
  assign _004_[3] = _058_ & ~(_046_);
  assign _059_ = parse_timeout_cnt[2] ^ _044_;
  assign _004_[2] = _051_ & _059_;
  assign _060_ = parse_timeout_cnt[0] ^ parse_timeout_cnt[1];
  assign _004_[1] = _051_ & _060_;
  assign _004_[0] = _051_ & ~(parse_timeout_cnt[0]);
  assign _061_ = boot_timeout_cnt[1] & boot_timeout_cnt[0];
  assign _062_ = boot_timeout_cnt[2] & _061_;
  assign _063_ = boot_timeout_cnt[3] & _062_;
  assign _064_ = fsm3_state[2] | fsm3_state[4];
  assign _065_ = boot_timeout_cnt[3] ^ _062_;
  assign _000_[3] = _064_ & _065_;
  assign _066_ = boot_timeout_cnt[2] ^ _061_;
  assign _000_[2] = _064_ & _066_;
  assign _067_ = _024_ | ~(fsm1_state[2]);
  assign _068_ = cdc_timeout_flag | fsm1_state[1];
  assign fsm1_next_state[1] = _067_ & _068_;
  assign _069_ = boot_timeout_cnt[1] ^ boot_timeout_cnt[0];
  assign _000_[1] = _064_ & _069_;
  assign _000_[0] = _023_ & _064_;
  assign _070_ = ~(isa_ready_sys_i & ISA_VALID);
  assign _071_ = _026_ & _070_;
  assign fsm1_next_state[0] = ~(cdc_timeout_flag | _071_);
  assign _072_ = boot_timeout_cnt[4] & _063_;
  assign _073_ = boot_timeout_cnt[4] | _063_;
  assign _074_ = _064_ & _073_;
  assign _000_[4] = _074_ & ~(_072_);
  assign _075_ = ~(fsm2_state[0] & ISA_VALID);
  assign _076_ = ~(fetch_count[0] | fetch_count[1]);
  assign _077_ = ~(ISA_VALID & _076_);
  assign _078_ = ~(parse_timeout_cnt[7] & _049_);
  assign _079_ = fsm2_state[6] & _078_;
  assign _080_ = ~(_077_ & _079_);
  assign _016_ = ~(_075_ & _080_);
  assign isa_access_grant_o = fsm3_state[1] | fsm3_state[6];
  assign _081_ = m16_enable_i & isa_access_grant_o;
  assign _006_ = _081_ & ~(sec_lockdown_i);
  assign _082_ = _064_ | isa_access_grant_o;
  assign _083_ = fsm3_state[0] | _082_;
  assign _084_ = sec_lockdown_i & _083_;
  assign _012_ = fsm3_state[5] | _084_;
  assign _085_ = fsm1_state[2] & fsm1_state[1];
  assign error_cdc_timeout_o = _085_ & ~(fsm1_state[0]);
  assign error_security_o = fsm3_state[5] | fsm3_state[3];
  assign _086_ = fsm2_state[6] | fsm2_state[3];
  assign _087_ = fsm2_state[0] | fsm2_state[6];
  assign _020_ = _086_ ? ISA_VALID : fsm2_state[0];
  assign _088_ = boot_timeout_cnt[5] & _072_;
  assign _089_ = boot_timeout_cnt[6] & _088_;
  assign _090_ = boot_timeout_cnt[7] & _089_;
  assign _091_ = ~(boot_timeout_cnt[7] & _089_);
  assign _017_ = ~(_064_ & _090_);
  assign _092_ = fetch_count[0] & ~(fetch_count[1]);
  assign _093_ = ~(ISA_VALID & _092_);
  assign _094_ = ~(fsm2_state[3] & _093_);
  assign _095_ = _077_ | ~(_079_);
  assign _015_ = ~(_094_ & _095_);
  assign _096_ = ~(_076_ & _078_);
  assign _097_ = fsm2_state[6] & ~(ISA_VALID);
  assign _098_ = ~(_096_ & _097_);
  assign _021_ = _087_ & _098_;
  assign _099_ = boot_timeout_cnt[7] | _089_;
  assign _100_ = _064_ & _099_;
  assign _000_[7] = _091_ & _100_;
  assign _101_ = ISA_VALID | ~(fsm2_state[0]);
  assign _102_ = ~(error_crc_o | fsm2_state[7]);
  assign _014_ = ~(_101_ & _102_);
  assign fsm1_next_state[2] = fsm1_state[2] ? _024_ : cdc_timeout_flag;
  assign _103_ = m16_enable_i | ~(isa_access_grant_o);
  assign _104_ = fsm3_state[2] & ~(sec_status_fail_i);
  assign _105_ = ~(sec_status_pass_i & _104_);
  assign _106_ = _103_ & _105_;
  assign _013_ = ~(sec_lockdown_i | _106_);
  assign _009_ = fsm2_state[3] & ~(_093_);
  assign _107_ = fsm1_state[2] | _027_;
  assign _108_ = ~(m16_mode_i[1] & _107_);
  assign _109_ = m16_mode_i[0] ? m16_mode_i[1] : _108_;
  assign ISA_DIR = _081_ & ~(_109_);
  assign _110_ = ~(cdc_timeout_cnt[7] & _033_);
  assign _019_ = _110_ | ~(_002_);
  assign _111_ = ~(fsm3_state[4] & _091_);
  assign _112_ = _104_ & ~(sec_status_pass_i);
  assign _113_ = _111_ & ~(_112_);
  assign _010_ = ~(sec_lockdown_i | _113_);
  assign _114_ = ~(sec_status_fail_i & fsm3_state[2]);
  assign _115_ = ~(fsm3_state[4] & _090_);
  assign _116_ = _114_ & _115_;
  assign _117_ = ~(sec_lockdown_i | _116_);
  assign _011_ = fsm3_state[3] | _117_;
  assign _018_ = ~(_002_ & _110_);
  assign _118_ = fsm3_state[0] & ~(sec_lockdown_i);
  assign _007_ = sec_boot_done_i & _118_;
  assign _005_ = _118_ & ~(sec_boot_done_i);
  assign _008_ = fsm2_state[6] & ~(_078_);
  assign _119_ = boot_timeout_cnt[6] | _088_;
  assign _120_ = _064_ & _119_;
  assign _000_[6] = _120_ & ~(_089_);
  assign _121_ = parse_timeout_cnt[7] | _049_;
  assign _122_ = _051_ & _121_;
  assign _004_[7] = _078_ & _122_;
  assign _123_ = cdc_timeout_cnt[7] | _033_;
  assign _001_[7] = _123_ & ~(_018_);
  assign _124_ = boot_timeout_cnt[5] | _072_;
  assign _125_ = _064_ & _124_;
  assign _000_[5] = _125_ & ~(_088_);
  assign _126_ = fetch_count[0] & fetch_count[1];
  assign _127_ = ~(fsm2_state[0] | _126_);
  assign _003_[1] = _127_ & ~(_076_);
  reg \fsm2_state_reg[0] ;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) \fsm2_state_reg[0]  <= 1'h1;
    else \fsm2_state_reg[0]  <= _014_;
  assign fsm2_state[0] = \fsm2_state_reg[0] ;
  reg \fsm2_state_reg[2] ;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) \fsm2_state_reg[2]  <= 1'h0;
    else \fsm2_state_reg[2]  <= fsm2_state[9];
  assign fsm2_state[2] = \fsm2_state_reg[2] ;
  reg \fsm2_state_reg[3] ;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) \fsm2_state_reg[3]  <= 1'h0;
    else \fsm2_state_reg[3]  <= _015_;
  assign fsm2_state[3] = \fsm2_state_reg[3] ;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) error_crc_o <= 1'h0;
    else error_crc_o <= fsm2_state[5];
  reg \fsm2_state_reg[5] ;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) \fsm2_state_reg[5]  <= 1'h0;
    else \fsm2_state_reg[5]  <= fsm2_state[8];
  assign fsm2_state[5] = \fsm2_state_reg[5] ;
  reg \fsm2_state_reg[6] ;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) \fsm2_state_reg[6]  <= 1'h0;
    else \fsm2_state_reg[6]  <= _016_;
  assign fsm2_state[6] = \fsm2_state_reg[6] ;
  reg \fsm2_state_reg[7] ;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) \fsm2_state_reg[7]  <= 1'h0;
    else \fsm2_state_reg[7]  <= _008_;
  assign fsm2_state[7] = \fsm2_state_reg[7] ;
  reg \fsm2_state_reg[8] ;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) \fsm2_state_reg[8]  <= 1'h0;
    else \fsm2_state_reg[8]  <= fsm2_state[2];
  assign fsm2_state[8] = \fsm2_state_reg[8] ;
  reg \fsm2_state_reg[9] ;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) \fsm2_state_reg[9]  <= 1'h0;
    else \fsm2_state_reg[9]  <= _009_;
  assign fsm2_state[9] = \fsm2_state_reg[9] ;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) parse_timeout_cnt[0] <= 1'h0;
    else if (_021_) parse_timeout_cnt[0] <= _004_[0];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) parse_timeout_cnt[1] <= 1'h0;
    else if (_021_) parse_timeout_cnt[1] <= _004_[1];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) parse_timeout_cnt[2] <= 1'h0;
    else if (_021_) parse_timeout_cnt[2] <= _004_[2];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) parse_timeout_cnt[3] <= 1'h0;
    else if (_021_) parse_timeout_cnt[3] <= _004_[3];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) parse_timeout_cnt[4] <= 1'h0;
    else if (_021_) parse_timeout_cnt[4] <= _004_[4];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) parse_timeout_cnt[5] <= 1'h0;
    else if (_021_) parse_timeout_cnt[5] <= _004_[5];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) parse_timeout_cnt[6] <= 1'h0;
    else if (_021_) parse_timeout_cnt[6] <= _004_[6];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) parse_timeout_cnt[7] <= 1'h0;
    else if (_021_) parse_timeout_cnt[7] <= _004_[7];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) cdc_timeout_cnt[0] <= 1'h0;
    else if (_019_) cdc_timeout_cnt[0] <= _001_[0];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) cdc_timeout_cnt[1] <= 1'h0;
    else if (_019_) cdc_timeout_cnt[1] <= _001_[1];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) cdc_timeout_cnt[2] <= 1'h0;
    else if (_019_) cdc_timeout_cnt[2] <= _001_[2];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) cdc_timeout_cnt[3] <= 1'h0;
    else if (_019_) cdc_timeout_cnt[3] <= _001_[3];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) cdc_timeout_cnt[4] <= 1'h0;
    else if (_019_) cdc_timeout_cnt[4] <= _001_[4];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) cdc_timeout_cnt[5] <= 1'h0;
    else if (_019_) cdc_timeout_cnt[5] <= _001_[5];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) cdc_timeout_cnt[6] <= 1'h0;
    else if (_019_) cdc_timeout_cnt[6] <= _001_[6];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) cdc_timeout_cnt[7] <= 1'h0;
    else if (_019_) cdc_timeout_cnt[7] <= _001_[7];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) cdc_timeout_flag <= 1'h0;
    else if (_018_) cdc_timeout_flag <= _002_;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) boot_timeout_cnt[0] <= 1'h0;
    else if (_017_) boot_timeout_cnt[0] <= _000_[0];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) boot_timeout_cnt[1] <= 1'h0;
    else if (_017_) boot_timeout_cnt[1] <= _000_[1];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) boot_timeout_cnt[2] <= 1'h0;
    else if (_017_) boot_timeout_cnt[2] <= _000_[2];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) boot_timeout_cnt[3] <= 1'h0;
    else if (_017_) boot_timeout_cnt[3] <= _000_[3];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) boot_timeout_cnt[4] <= 1'h0;
    else if (_017_) boot_timeout_cnt[4] <= _000_[4];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) boot_timeout_cnt[5] <= 1'h0;
    else if (_017_) boot_timeout_cnt[5] <= _000_[5];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) boot_timeout_cnt[6] <= 1'h0;
    else if (_017_) boot_timeout_cnt[6] <= _000_[6];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) boot_timeout_cnt[7] <= 1'h0;
    else if (_017_) boot_timeout_cnt[7] <= _000_[7];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) fetch_count[0] <= 1'h0;
    else if (_020_) fetch_count[0] <= _003_[0];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) fetch_count[1] <= 1'h0;
    else if (_020_) fetch_count[1] <= _003_[1];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) fsm3_state[0] <= 1'h1;
    else fsm3_state[0] <= _005_;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) fsm3_state[1] <= 1'h0;
    else fsm3_state[1] <= _006_;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) fsm3_state[2] <= 1'h0;
    else fsm3_state[2] <= _010_;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) fsm3_state[3] <= 1'h0;
    else fsm3_state[3] <= _011_;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) fsm3_state[4] <= 1'h0;
    else fsm3_state[4] <= _007_;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) fsm3_state[5] <= 1'h0;
    else fsm3_state[5] <= _012_;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) fsm3_state[6] <= 1'h0;
    else fsm3_state[6] <= _013_;
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) fsm1_state[0] <= 1'h0;
    else fsm1_state[0] <= fsm1_next_state[0];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) fsm1_state[1] <= 1'h0;
    else fsm1_state[1] <= fsm1_next_state[1];
  always @(posedge clk_sys_i, negedge rst_sys_n_sync2)
    if (!rst_sys_n_sync2) fsm1_state[2] <= 1'h0;
    else fsm1_state[2] <= fsm1_next_state[2];
  always @(posedge clk_sys_i, negedge m16_reset_n_i)
    if (!m16_reset_n_i) rst_sys_n_sync1 <= 1'h0;
    else rst_sys_n_sync1 <= 1'h1;
  always @(posedge clk_sys_i, negedge m16_reset_n_i)
    if (!m16_reset_n_i) rst_sys_n_sync2 <= 1'h0;
    else rst_sys_n_sync2 <= rst_sys_n_sync1;
  assign { fsm2_state[10], fsm2_state[4], fsm2_state[1] } = { 1'h0, error_crc_o, 1'h0 };
  assign error_invalid_opcode_o = 1'h0;
  assign isa_crc_error_o = error_crc_o;
  assign isa_access_denied_o = error_security_o;
  assign isa_pc_o = 32'd0;
  assign isa_req_sys_o = ISA_VALID;
  assign isa_valid_sys_o = 1'h0;
  assign isa_data_sys_o = 32'd0;
  assign ISA_IF = 16'hxxxx;
endmodule
