// DRAM_AXI_VIP.sv
// Verification IP for DRAM with AXI4 Interface
// Data Width: 1024 bits, Clock: 1 GHz
//
// Generated by bb-vip skill
// Configuration: Read Latency 50 cycles, Write Latency 20 cycles

`timescale 1ns/1ps

module DRAM_AXI_VIP #(
    // Clock Parameters
    parameter int CLK_PERIOD_NS   = 1,       // 1 GHz clock period

    // Memory Configuration
    parameter int DATA_WIDTH      = 1024,    // AXI data width (bits)
    parameter int STRB_WIDTH      = DATA_WIDTH / 8, // 128 bytes strobe
    parameter int ID_WIDTH        = 8,       // AXI ID width
    parameter longint MEM_SIZE_B  = 268435456, // Default: 256MB (250GB specified, using 256MB as realistic default)

    // Derived Parameters
    parameter int ADDR_WIDTH      = $clog2(MEM_SIZE_B),
    parameter int MEM_DEPTH       = MEM_SIZE_B / (DATA_WIDTH / 8), // Number of 128-byte entries

    // Latency Parameters (in clock cycles)
    parameter int READ_LATENCY    = 50,      // Read latency cycles
    parameter int WRITE_LATENCY   = 20,      // Write latency cycles

    // Burst Configuration
    parameter int BURST_MAX       = 256,     // Maximum burst length

    // Error Injection
    parameter bit ERROR_INJECT    = 0,       // Enable error injection
    parameter int ERROR_RATE_PPM  = 0        // Error rate (parts per million)
)(
    // Clock and Reset
    input  logic                   clk,
    input  logic                   rst_n,

    // AXI Write Address Channel
    input  logic                   aw_valid,
    output logic                   aw_ready,
    input  logic [ADDR_WIDTH-1:0]  aw_addr,
    input  logic [ID_WIDTH-1:0]    aw_id,
    input  logic [7:0]             aw_len,    // Burst length - 1
    input  logic [2:0]             aw_size,   // Transfer size (5 = 1024 bits)
    input  logic [1:0]             aw_burst,  // Burst type (00=FIXED, 01=INCR, 10=WRAP)

    // AXI Write Data Channel
    input  logic                   w_valid,
    output logic                   w_ready,
    input  logic [DATA_WIDTH-1:0]  w_data,
    input  logic [STRB_WIDTH-1:0]  w_strb,
    input  logic                   w_last,

    // AXI Write Response Channel
    output logic                   b_valid,
    input  logic                   b_ready,
    output logic [1:0]             b_resp,    // 00=OKAY, 01=EXOKAY, 10=SLVERR, 11=DECERR
    output logic [ID_WIDTH-1:0]    b_id,

    // AXI Read Address Channel
    input  logic                   ar_valid,
    output logic                   ar_ready,
    input  logic [ADDR_WIDTH-1:0]  ar_addr,
    input  logic [ID_WIDTH-1:0]    ar_id,
    input  logic [7:0]             ar_len,
    input  logic [2:0]             ar_size,
    input  logic [1:0]             ar_burst,

    // AXI Read Data Channel
    output logic                   r_valid,
    input  logic                   r_ready,
    output logic [DATA_WIDTH-1:0]  r_data,
    output logic [1:0]             r_resp,
    output logic                   r_last,
    output logic [ID_WIDTH-1:0]    r_id,

    // Status Outputs
    output logic                   mem_ready,
    output logic [31:0]            mem_usage
);

    // ========================================================================
    // Internal Memory Model
    // ========================================================================

    // Use associative array for flexible memory size
    // Address index is in units of DATA_WIDTH (128-byte chunks)
    logic [DATA_WIDTH-1:0] mem_storage [*];

    // Transaction Tracking
    typedef struct {
        logic [ADDR_WIDTH-1:0] base_addr;
        logic [ID_WIDTH-1:0]   id;
        logic [7:0]            len;
        logic [2:0]            size;
        logic [1:0]            burst;
        int                    beat_count;
        logic                  is_write;
    } transaction_t;

    transaction_t wr_txn;
    transaction_t rd_txn;

    // Response FIFO
    typedef struct {
        logic [DATA_WIDTH-1:0] data;
        logic [1:0]            resp;
        logic                  last;
        logic [ID_WIDTH-1:0]   id;
    } rd_response_t;

    rd_response_t rd_resp_fifo [$];
    logic         rd_resp_valid;
    rd_response_t rd_resp_current;

    // Write Response Queue
    typedef struct {
        logic [1:0]            resp;
        logic [ID_WIDTH-1:0]   id;
    } wr_response_t;

    wr_response_t wr_resp_queue [$];

    // Latency Counter
    int latency_counter;
    int pending_rd_count;
    int pending_wr_count;

    // ========================================================================
    // Memory Statistics
    // ========================================================================

    int total_entries_used;
    always @(posedge clk) begin
        mem_usage = total_entries_used * (DATA_WIDTH / 8);
    end

    // ========================================================================
    // AXI Protocol Handling - Write Channel
    // ========================================================================

    // Write Address Phase
    logic wr_addr_accepted;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            wr_addr_accepted = 0;
            aw_ready = 1;
            wr_txn = '0;
        end else begin
            if (aw_valid && aw_ready && !wr_addr_accepted) begin
                // Accept write address
                wr_txn.base_addr  = aw_addr;
                wr_txn.id         = aw_id;
                wr_txn.len        = aw_len;
                wr_txn.size       = aw_size;
                wr_txn.burst      = aw_burst;
                wr_txn.beat_count = 0;
                wr_txn.is_write   = 1;
                wr_addr_accepted  = 1;
                aw_ready = 0;  // Hold ready after acceptance

                $display("[%0t] DRAM_VIP: Write Addr Accepted - ID=%0h, Addr=%0h, Len=%0d",
                         $time, aw_id, aw_addr, aw_len + 1);
            end
        end
    end

    // Write Data Phase
    logic wr_data_phase_active;
    int  wr_latency_cnt;
    logic [ADDR_WIDTH-1:0] wr_current_addr;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            w_ready = 1;
            wr_data_phase_active = 0;
            wr_latency_cnt = 0;
            wr_current_addr = 0;
        end else begin
            if (wr_addr_accepted && w_valid && w_ready) begin
                // Calculate current address based on burst mode
                case (wr_txn.burst)
                    2'b00: wr_current_addr = wr_txn.base_addr; // FIXED
                    2'b01: wr_current_addr = wr_txn.base_addr + (wr_txn.beat_count * (DATA_WIDTH/8)); // INCR
                    2'b10: wr_current_addr = wr_txn.base_addr + // WRAP
                             ((wr_txn.beat_count % (wr_txn.len + 1)) * (DATA_WIDTH/8));
                    default: wr_current_addr = wr_txn.base_addr;
                endcase

                // Store data with strobe masking
                logic [DATA_WIDTH-1:0] stored_data;
                logic [ADDR_WIDTH-$clog2(DATA_WIDTH/8)-1:0] mem_idx;
                mem_idx = wr_current_addr / (DATA_WIDTH/8);

                if (mem_storage.exists(mem_idx)) begin
                    stored_data = mem_storage[mem_idx];
                end else begin
                    stored_data = '0;
                    total_entries_used++;
                end

                // Apply write strobe
                for (int i = 0; i < STRB_WIDTH; i++) begin
                    if (w_strb[i]) begin
                        stored_data[i*8 +: 8] = w_data[i*8 +: 8];
                    end
                end
                mem_storage[mem_idx] = stored_data;

                $display("[%0t] DRAM_VIP: Write Beat %0d - Addr=%0h, Data[0:31]=%0h",
                         $time, wr_txn.beat_count, wr_current_addr, w_data[31:0]);

                wr_txn.beat_count++;

                // Check for last beat
                if (w_last || wr_txn.beat_count == wr_txn.len + 1) begin
                    w_ready = 0;
                    wr_data_phase_active = 1;
                    wr_latency_cnt = WRITE_LATENCY;
                    wr_addr_accepted = 0;
                    $display("[%0t] DRAM_VIP: Write Burst Complete, Latency Counter Started (%0d cycles)",
                             $time, WRITE_LATENCY);
                end
            end

            // Write latency countdown
            if (wr_data_phase_active) begin
                if (wr_latency_cnt > 0) begin
                    wr_latency_cnt--;
                end else begin
                    // Generate write response
                    wr_response_t wr_resp;
                    wr_resp.resp = ERROR_INJECT && ($urandom % 1000000 < ERROR_RATE_PPM) ? 2'b10 : 2'b00;
                    wr_resp.id = wr_txn.id;
                    wr_resp_queue.push_back(wr_resp);
                    wr_data_phase_active = 0;
                    w_ready = 1;
                    aw_ready = 1;
                    $display("[%0t] DRAM_VIP: Write Response Queued - ID=%0h, Resp=%0h",
                             $time, wr_resp.id, wr_resp.resp);
                end
            end
        end
    end

    // Write Response Phase
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            b_valid = 0;
            b_resp = 0;
            b_id = 0;
        end else begin
            if (!b_valid && wr_resp_queue.size() > 0) begin
                wr_response_t wr_resp = wr_resp_queue.pop_front();
                b_valid = 1;
                b_resp = wr_resp.resp;
                b_id = wr_resp.id;
            end else if (b_valid && b_ready) begin
                b_valid = 0;
            end
        end
    end

    // ========================================================================
    // AXI Protocol Handling - Read Channel
    // ========================================================================

    // Read Address Phase
    logic rd_addr_accepted;
    logic rd_data_phase_active;
    int  rd_latency_cnt;
    logic [ADDR_WIDTH-1:0] rd_current_addr;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            ar_ready = 1;
            rd_addr_accepted = 0;
            rd_data_phase_active = 0;
            rd_txn = '0;
        end else begin
            // Accept read address
            if (ar_valid && ar_ready && !rd_addr_accepted) begin
                rd_txn.base_addr  = ar_addr;
                rd_txn.id         = ar_id;
                rd_txn.len        = ar_len;
                rd_txn.size       = ar_size;
                rd_txn.burst      = ar_burst;
                rd_txn.beat_count = 0;
                rd_txn.is_write   = 0;
                rd_addr_accepted  = 1;
                ar_ready = 0;

                $display("[%0t] DRAM_VIP: Read Addr Accepted - ID=%0h, Addr=%0h, Len=%0d",
                         $time, ar_id, ar_addr, ar_len + 1);
            end

            // Read latency handling
            if (rd_addr_accepted && !rd_data_phase_active) begin
                rd_data_phase_active = 1;
                rd_latency_cnt = READ_LATENCY;
                $display("[%0t] DRAM_VIP: Read Latency Started (%0d cycles)",
                         $time, READ_LATENCY);
            end

            // Read latency countdown and data generation
            if (rd_data_phase_active) begin
                if (rd_latency_cnt > 0) begin
                    rd_latency_cnt--;
                end else begin
                    // Generate read data beat
                    case (rd_txn.burst)
                        2'b00: rd_current_addr = rd_txn.base_addr;
                        2'b01: rd_current_addr = rd_txn.base_addr + (rd_txn.beat_count * (DATA_WIDTH/8));
                        2'b10: rd_current_addr = rd_txn.base_addr +
                                 ((rd_txn.beat_count % (rd_txn.len + 1)) * (DATA_WIDTH/8));
                        default: rd_current_addr = rd_txn.base_addr;
                    endcase

                    logic [ADDR_WIDTH-$clog2(DATA_WIDTH/8)-1:0] mem_idx;
                    mem_idx = rd_current_addr / (DATA_WIDTH/8);

                    rd_response_t rd_resp_entry;
                    rd_resp_entry.id = rd_txn.id;

                    // Read from memory (or return zeros if not initialized)
                    if (mem_storage.exists(mem_idx)) begin
                        rd_resp_entry.data = mem_storage[mem_idx];
                    end else begin
                        rd_resp_entry.data = '0;
                    end

                    // Error injection
                    if (ERROR_INJECT && ($urandom % 1000000 < ERROR_RATE_PPM)) begin
                        rd_resp_entry.resp = 2'b10; // SLVERR
                        rd_resp_entry.data = rd_resp_entry.data ^ $urandom;
                    end else begin
                        rd_resp_entry.resp = 2'b00; // OKAY
                    end

                    rd_resp_entry.last = (rd_txn.beat_count == rd_txn.len);
                    rd_resp_fifo.push_back(rd_resp_entry);

                    $display("[%0t] DRAM_VIP: Read Beat %0d Generated - Addr=%0h, Data[0:31]=%0h",
                             $time, rd_txn.beat_count, rd_current_addr, rd_resp_entry.data[31:0]);

                    rd_txn.beat_count++;

                    // Check if burst complete
                    if (rd_txn.beat_count == rd_txn.len + 1) begin
                        rd_data_phase_active = 0;
                        rd_addr_accepted = 0;
                        ar_ready = 1;
                    end else begin
                        // Continue generating beats with 1 cycle gap
                        rd_latency_cnt = 1;
                    end
                end
            end
        end
    end

    // Read Response Phase
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            r_valid = 0;
            r_data = 0;
            r_resp = 0;
            r_last = 0;
            r_id = 0;
        end else begin
            if (!r_valid && rd_resp_fifo.size() > 0) begin
                rd_resp_current = rd_resp_fifo.pop_front();
                r_valid = 1;
                r_data = rd_resp_current.data;
                r_resp = rd_resp_current.resp;
                r_last = rd_resp_current.last;
                r_id = rd_resp_current.id;
            end else if (r_valid && r_ready) begin
                r_valid = 0;
                if (r_last) begin
                    $display("[%0t] DRAM_VIP: Read Burst Complete - ID=%0h", $time, r_id);
                end
            end
        end
    end

    // ========================================================================
    // Memory Ready Indicator
    // ========================================================================

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            mem_ready = 0;
        end else begin
            // Memory ready when not processing transactions
            mem_ready = !rd_data_phase_active && !wr_data_phase_active &&
                        rd_resp_fifo.size() == 0 && wr_resp_queue.size() == 0;
        end
    end

    // ========================================================================
    // Task API for Testbench Integration
    // ========================================================================

    // Task: Initialize Memory with Pattern
    task init_memory_pattern(input logic [DATA_WIDTH-1:0] pattern);
        logic [ADDR_WIDTH-$clog2(DATA_WIDTH/8)-1:0] idx;
        for (idx = 0; idx < MEM_DEPTH; idx++) begin
            mem_storage[idx] = pattern;
        end
        total_entries_used = MEM_DEPTH;
        $display("[%0t] DRAM_VIP: Memory Initialized with Pattern %0h", $time, pattern);
    endtask

    // Task: Load Memory from Hex File
    task load_memory_file(input string filename);
        $readmemh(filename, mem_storage);
        $display("[%0t] DRAM_VIP: Memory Loaded from File %s", $time, filename);
    endtask

    // Task: Dump Memory to Hex File
    task dump_memory_file(input string filename);
        $writememh(filename, mem_storage);
        $display("[%0t] DRAM_VIP: Memory Dumped to File %s", $time, filename);
    endtask

    // Task: Direct Write (Backdoor Access)
    task backdoor_write(
        input logic [ADDR_WIDTH-1:0] addr,
        input logic [DATA_WIDTH-1:0] data
    );
        logic [ADDR_WIDTH-$clog2(DATA_WIDTH/8)-1:0] mem_idx;
        mem_idx = addr / (DATA_WIDTH/8);
        mem_storage[mem_idx] = data;
        $display("[%0t] DRAM_VIP: Backdoor Write - Addr=%0h, Data=%0h", $time, addr, data);
    endtask

    // Task: Direct Read (Backdoor Access)
    task backdoor_read(
        input  logic [ADDR_WIDTH-1:0] addr,
        output logic [DATA_WIDTH-1:0] data
    );
        logic [ADDR_WIDTH-$clog2(DATA_WIDTH/8)-1:0] mem_idx;
        mem_idx = addr / (DATA_WIDTH/8);
        if (mem_storage.exists(mem_idx)) begin
            data = mem_storage[mem_idx];
        end else begin
            data = '0;
        end
        $display("[%0t] DRAM_VIP: Backdoor Read - Addr=%0h, Data=%0h", $time, addr, data);
    endtask

    // Task: Force Error Injection
    task force_error(input int rate_ppm);
        ERROR_RATE_PPM = rate_ppm;
        $display("[%0t] DRAM_VIP: Error Rate Set to %0d ppm", $time, rate_ppm);
    endtask

    // Task: Get Memory Statistics
    task get_stats(
        output int entries_used,
        output int bytes_used
    );
        entries_used = total_entries_used;
        bytes_used = mem_usage;
    endtask

    // ========================================================================
    // Configuration Display
    // ========================================================================

    initial begin
        $display("========================================");
        $display("DRAM_AXI_VIP Configuration:");
        $display("  Data Width    : %0d bits", DATA_WIDTH);
        $display("  Address Width : %0d bits", ADDR_WIDTH);
        $display("  Memory Size   : %0d bytes (%0.2f MB)", MEM_SIZE_B, MEM_SIZE_B / 1048576.0);
        $display("  Read Latency  : %0d cycles", READ_LATENCY);
        $display("  Write Latency : %0d cycles", WRITE_LATENCY);
        $display("  Error Inject  : %0s", ERROR_INJECT ? "ENABLED" : "DISABLED");
        $display("========================================");
    end

endmodule