// {{ PARENT_MODULE }}.sv
// Generated by rtl-coder from spec_mas/{{ MODULE_PATH }}
// ---
// module: {{ MODULE_ID }}
// type: rtl
// status: pending
// parent: {{ PARENT_ID }}
// synthesizable: true
// clock_domain: {{ DOMAIN_NAME }}
// generated: {{ TIMESTAMP }}
// ---

module {{ PARENT_MODULE }} (
    // ============================================
    // Top-level Ports (from MAS.md)
    // ============================================
    input  logic        clk,
    input  logic        rst_n,

    input  logic              valid_in,
    input  logic [WIDTH-1:0]  data_in,

    output logic              valid_out,
    output logic [WIDTH-1:0]  data_out
);

    // ============================================
    // Inter-module Connections
    // ============================================
    logic [WIDTH-1:0] {{ interconnect_signal_1 }};
    logic             {{ interconnect_signal_2 }};
    // TODO: Define inter-module signals

    // ============================================
    // Sub-module Instantiations
    // ============================================
    {{ SUB_MODULE_1 }} u_{{ SUB_MODULE_1 }} (
        .clk     (clk),
        .rst_n   (rst_n),
        .valid_in(valid_in),
        .data_in (data_in),
        .valid_out({{ interconnect_signal_2 }}),
        .data_out ({{ interconnect_signal_1 }})
    );

    {{ SUB_MODULE_2 }} u_{{ SUB_MODULE_2 }} (
        .clk     (clk),
        .rst_n   (rst_n),
        .valid_in({{ interconnect_signal_2 }}),
        .data_in ({{ interconnect_signal_1 }}),
        .valid_out(valid_out),
        .data_out (data_out)
    );

    // ============================================
    // Top-level FSM Coordination
    // ============================================
    {{ top_fsm_logic }}

endmodule