// {{ MODULE_NAME }}.sv
// Generated by rtl-coder from spec_mas/{{ MODULE_PATH }}
// ---
// module: {{ MODULE_ID }}
// type: rtl
// status: pending
// parent: {{ PARENT_ID }}
// synthesizable: true
// clock_domain: {{ DOMAIN_NAME }}
// generated: {{ TIMESTAMP }}
// ---

module {{ MODULE_NAME }} (
    // ============================================
    // Clock & Reset
    // ============================================
    input  logic        clk,
    input  logic        rst_n,

    // ============================================
    // Input Ports (from MAS.md §2.1)
    // ============================================
    input  logic              valid_in,
    input  logic [WIDTH-1:0]  data_in,
    // TODO: Add more input ports from MAS.md

    // ============================================
    // Output Ports (from MAS.md §2.1)
    // ============================================
    output logic              valid_out,
    output logic [WIDTH-1:0]  data_out,
    // TODO: Add more output ports from MAS.md
);

    // ============================================
    // FSM States (from FSM.md)
    // ============================================
    typedef enum logic [{{ STATE_WIDTH-1 }}:0] {
        IDLE    = {{ IDLE_ENCODING }},
        ACTIVE  = {{ ACTIVE_ENCODING }},
        DONE    = {{ DONE_ENCODING }}
        // TODO: Add more states from FSM.md
    } state_t;

    state_t current_state, next_state;

    // ============================================
    // Datapath Registers (from datapath.md)
    // ============================================
    logic [WIDTH-1:0] {{ reg_name }};
    // TODO: Add more registers from datapath.md

    // ============================================
    // FSM Sequential Logic
    // ============================================
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            current_state <= IDLE;
            {{ reset_assignments }}
        end else begin
            current_state <= next_state;
            {{ sequential_assignments }}
        end
    end

    // ============================================
    // FSM Combinational Logic
    // ============================================
    always_comb begin
        next_state = current_state;
        case (current_state)
            IDLE:   if ({{ start_condition }}) next_state = ACTIVE;
            ACTIVE: if ({{ done_condition }})  next_state = DONE;
            DONE:   next_state = IDLE;
            default: next_state = IDLE;
        endcase
    end

    // ============================================
    // Output Logic
    // ============================================
    always_comb begin
        valid_out = (current_state == DONE);
        data_out  = {{ output_value }};
    end

    // ============================================
    // Datapath Logic (from datapath.md)
    // ============================================
    {{ datapath_logic }}

endmodule