/* Generated by Yosys 0.65+37 (git sha1 e87a9bd9a, clang++ 18.1.8 -fPIC -O3) */

module NPU_top(ext_clk_50MHz, ext_rst_por_n, pll_pwr_en, irq_compute_done);
  input ext_clk_50MHz;
  wire ext_clk_50MHz;
  input ext_rst_por_n;
  wire ext_rst_por_n;
  output pll_pwr_en;
  wire pll_pwr_en;
  output irq_compute_done;
  wire irq_compute_done;
  assign irq_compute_done = 1'h0;
  assign pll_pwr_en = ext_rst_por_n;
endmodule
